// Generated by CIRCT firtool-1.30.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module RouteComputer_70(
  input  [2:0] io_req_3_bits_src_virt_id,
               io_req_3_bits_flow_vnet_id,
  input  [6:0] io_req_3_bits_flow_ingress_node,
  input  [1:0] io_req_3_bits_flow_ingress_node_id,
  input  [6:0] io_req_3_bits_flow_egress_node,
  input  [1:0] io_req_3_bits_flow_egress_node_id,
  input  [2:0] io_req_2_bits_src_virt_id,
               io_req_2_bits_flow_vnet_id,
  input  [6:0] io_req_2_bits_flow_ingress_node,
  input  [1:0] io_req_2_bits_flow_ingress_node_id,
  input  [6:0] io_req_2_bits_flow_egress_node,
  input  [1:0] io_req_2_bits_flow_egress_node_id,
  input  [2:0] io_req_1_bits_src_virt_id,
               io_req_1_bits_flow_vnet_id,
  input  [6:0] io_req_1_bits_flow_ingress_node,
  input  [1:0] io_req_1_bits_flow_ingress_node_id,
  input  [6:0] io_req_1_bits_flow_egress_node,
  input  [1:0] io_req_1_bits_flow_egress_node_id,
  input  [2:0] io_req_0_bits_src_virt_id,
               io_req_0_bits_flow_vnet_id,
  input  [6:0] io_req_0_bits_flow_ingress_node,
  input  [1:0] io_req_0_bits_flow_ingress_node_id,
  input  [6:0] io_req_0_bits_flow_egress_node,
  input  [1:0] io_req_0_bits_flow_egress_node_id,
  output       io_resp_3_vc_sel_2_1,
               io_resp_3_vc_sel_2_2,
               io_resp_3_vc_sel_2_3,
               io_resp_3_vc_sel_2_4,
               io_resp_3_vc_sel_1_1,
               io_resp_3_vc_sel_1_2,
               io_resp_3_vc_sel_1_3,
               io_resp_3_vc_sel_1_4,
               io_resp_2_vc_sel_3_0,
               io_resp_2_vc_sel_3_1,
               io_resp_2_vc_sel_3_2,
               io_resp_2_vc_sel_3_3,
               io_resp_2_vc_sel_3_4,
               io_resp_2_vc_sel_1_1,
               io_resp_2_vc_sel_1_2,
               io_resp_2_vc_sel_1_3,
               io_resp_2_vc_sel_1_4,
               io_resp_2_vc_sel_0_4,
               io_resp_1_vc_sel_0_4,
               io_resp_0_vc_sel_3_1,
               io_resp_0_vc_sel_3_2,
               io_resp_0_vc_sel_3_3,
               io_resp_0_vc_sel_3_4,
               io_resp_0_vc_sel_2_1,
               io_resp_0_vc_sel_2_2,
               io_resp_0_vc_sel_2_3,
               io_resp_0_vc_sel_2_4,
               io_resp_0_vc_sel_1_1,
               io_resp_0_vc_sel_1_2,
               io_resp_0_vc_sel_1_3,
               io_resp_0_vc_sel_1_4
);

  wire [4:0]  _GEN = ~(io_req_0_bits_flow_egress_node[4:0]);	// RouteComputer.scala:74:27, pla.scala:78:21
  wire [3:0]  _decoded_T = {_GEN[1], _GEN[2], _GEN[4], io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_2 =
    {io_req_0_bits_flow_egress_node[1], _GEN[2], _GEN[3], io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_4 =
    {_GEN[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_6 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_8 =
    {io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_10 =
    {_GEN[1], io_req_0_bits_flow_egress_node[3], _GEN[4], io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_12 =
    {_GEN[0],
     io_req_0_bits_flow_egress_node[1],
     _GEN[2],
     io_req_0_bits_flow_egress_node[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_14 =
    {io_req_0_bits_flow_egress_node[0],
     io_req_0_bits_flow_egress_node[1],
     _GEN[2],
     io_req_0_bits_flow_egress_node[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_16 =
    {io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:90:45
  wire [5:0]  _decoded_T_18 =
    {_GEN[0],
     _GEN[1],
     _GEN[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_20 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     _GEN[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_22 =
    {_GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_24 =
    {_GEN[0],
     io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_26 =
    {io_req_0_bits_flow_egress_node[0],
     io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_28 =
    {_GEN[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_30 =
    {_GEN[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_32 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_34 = {_GEN[1], _GEN[2], _GEN[4], io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_36 =
    {io_req_0_bits_flow_egress_node[1], _GEN[2], _GEN[3], io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_38 =
    {_GEN[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_40 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_42 =
    {io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_44 =
    {_GEN[1], _GEN[2], io_req_0_bits_flow_egress_node[3], io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_46 =
    {_GEN[1], io_req_0_bits_flow_egress_node[3], _GEN[4], io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_48 =
    {_GEN[0],
     io_req_0_bits_flow_egress_node[1],
     _GEN[2],
     io_req_0_bits_flow_egress_node[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_50 =
    {io_req_0_bits_flow_egress_node[0],
     io_req_0_bits_flow_egress_node[1],
     _GEN[2],
     io_req_0_bits_flow_egress_node[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_52 =
    {_GEN[0],
     _GEN[1],
     _GEN[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_54 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     _GEN[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_56 =
    {_GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_58 =
    {_GEN[0],
     io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_60 =
    {io_req_0_bits_flow_egress_node[0],
     io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_62 =
    {io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:90:45
  wire [5:0]  _decoded_T_64 =
    {_GEN[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_66 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_68 = {_GEN[1], _GEN[2], _GEN[4], io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_70 =
    {io_req_0_bits_flow_egress_node[1], _GEN[2], _GEN[3], io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_72 =
    {_GEN[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_74 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_76 =
    {io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_78 =
    {_GEN[1], _GEN[2], io_req_0_bits_flow_egress_node[3], io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_80 =
    {_GEN[1], io_req_0_bits_flow_egress_node[3], _GEN[4], io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_82 =
    {_GEN[0],
     io_req_0_bits_flow_egress_node[1],
     _GEN[2],
     io_req_0_bits_flow_egress_node[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_84 =
    {io_req_0_bits_flow_egress_node[0],
     io_req_0_bits_flow_egress_node[1],
     _GEN[2],
     io_req_0_bits_flow_egress_node[3],
     _GEN[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_86 =
    {_GEN[0],
     _GEN[1],
     _GEN[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_88 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     _GEN[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_90 =
    {_GEN[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_92 =
    {_GEN[0],
     io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_94 =
    {io_req_0_bits_flow_egress_node[0],
     io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[2],
     _GEN[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_96 =
    {io_req_0_bits_flow_egress_node[1],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:90:45
  wire [5:0]  _decoded_T_98 =
    {_GEN[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_100 =
    {io_req_0_bits_flow_egress_node[0],
     _GEN[1],
     io_req_0_bits_flow_egress_node[2],
     io_req_0_bits_flow_egress_node[3],
     io_req_0_bits_flow_egress_node[4],
     io_req_0_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [20:0] _GEN_0 =
    ~{io_req_2_bits_flow_vnet_id,
      io_req_2_bits_flow_ingress_node,
      io_req_2_bits_flow_ingress_node_id,
      io_req_2_bits_flow_egress_node,
      io_req_2_bits_flow_egress_node_id};	// RouteComputer.scala:74:27, pla.scala:78:21
  wire [1:0]  _decoded_T_203 = {_GEN_0[0], _GEN_0[20]};	// Cat.scala:33:92, pla.scala:78:21, :91:29
  wire [2:0]  _decoded_T_205 =
    {io_req_2_bits_flow_egress_node_id[0], _GEN_0[2], io_req_2_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [2:0]  _decoded_T_207 =
    {io_req_2_bits_flow_egress_node[0], _GEN_0[7], io_req_2_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [2:0]  _decoded_T_209 =
    {io_req_2_bits_flow_egress_node_id[0], _GEN_0[2], io_req_2_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [2:0]  _decoded_T_213 =
    {io_req_2_bits_flow_egress_node_id[0],
     io_req_2_bits_flow_egress_node[0],
     io_req_2_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:90:45
  wire [2:0]  _decoded_T_217 =
    {io_req_2_bits_flow_egress_node_id[0], _GEN_0[2], io_req_2_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [2:0]  _decoded_T_223 =
    {io_req_2_bits_flow_egress_node_id[0],
     io_req_2_bits_flow_egress_node[0],
     io_req_2_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:90:45
  wire [3:0]  _GEN_1 = ~(io_req_3_bits_flow_egress_node[4:1]);	// RouteComputer.scala:74:27, pla.scala:78:21
  wire [4:0]  _decoded_T_275 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_277 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_279 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_281 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_283 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_285 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_287 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:90:45
  wire [5:0]  _decoded_T_289 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_291 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_293 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_295 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_297 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_299 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_301 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_303 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_305 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_307 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_309 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_311 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_313 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_315 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_317 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_319 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:90:45
  wire [5:0]  _decoded_T_321 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_323 =
    {_GEN_1[0],
     _GEN_1[1],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_325 =
    {io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_327 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_329 =
    {io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_331 =
    {_GEN_1[0],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_333 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_335 =
    {io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_337 =
    {_GEN_1[0],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_339 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_341 =
    {io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_343 =
    {io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:90:45
  wire [5:0]  _decoded_T_345 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[0],
     io_req_3_bits_src_virt_id[1]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_347 =
    {_GEN_1[0], _GEN_1[1], _GEN_1[3], io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_349 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_351 =
    {io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_353 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_355 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_357 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_359 =
    {io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_361 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_363 =
    {_GEN_1[0],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_365 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_367 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_369 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_371 =
    {io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_373 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     _GEN_1[1],
     io_req_3_bits_flow_egress_node[3],
     _GEN_1[3],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_375 =
    {_GEN_1[0],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_377 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     _GEN_1[1],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_379 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_381 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [4:0]  _decoded_T_383 =
    {io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_385 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[2],
     _GEN_1[2],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [3:0]  _decoded_T_387 =
    {io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:90:45
  wire [4:0]  _decoded_T_389 =
    {io_req_3_bits_flow_egress_node_id[0],
     io_req_3_bits_flow_egress_node[1],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:90:45
  wire [4:0]  _decoded_T_391 =
    {_GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  wire [5:0]  _decoded_T_393 =
    {io_req_3_bits_flow_egress_node_id[0],
     _GEN_1[0],
     io_req_3_bits_flow_egress_node[2],
     io_req_3_bits_flow_egress_node[3],
     io_req_3_bits_flow_egress_node[4],
     io_req_3_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29
  assign io_resp_3_vc_sel_2_1 =
    |{&_decoded_T_275,
      &_decoded_T_277,
      &_decoded_T_281,
      &_decoded_T_283,
      &_decoded_T_287,
      &_decoded_T_291,
      &_decoded_T_295,
      &_decoded_T_299,
      &_decoded_T_301,
      &_decoded_T_305,
      &_decoded_T_307,
      &_decoded_T_309,
      &_decoded_T_315,
      &_decoded_T_319,
      &_decoded_T_349,
      &_decoded_T_353,
      &_decoded_T_361,
      &_decoded_T_367,
      &_decoded_T_369,
      &_decoded_T_381,
      &_decoded_T_389};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_3_vc_sel_2_2 =
    |{&_decoded_T_275,
      &_decoded_T_277,
      &_decoded_T_281,
      &_decoded_T_283,
      &_decoded_T_287,
      &_decoded_T_291,
      &_decoded_T_295,
      &_decoded_T_299,
      &_decoded_T_301,
      &_decoded_T_305,
      &_decoded_T_307,
      &_decoded_T_309,
      &_decoded_T_315,
      &_decoded_T_319,
      &_decoded_T_349,
      &_decoded_T_353,
      &_decoded_T_361,
      &_decoded_T_367,
      &_decoded_T_369,
      &_decoded_T_381,
      &_decoded_T_389};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_3_vc_sel_2_3 =
    |{&_decoded_T_275,
      &_decoded_T_277,
      &_decoded_T_281,
      &_decoded_T_283,
      &_decoded_T_287,
      &_decoded_T_291,
      &_decoded_T_295,
      &_decoded_T_299,
      &_decoded_T_301,
      &_decoded_T_305,
      &_decoded_T_307,
      &_decoded_T_309,
      &_decoded_T_315,
      &_decoded_T_319,
      &_decoded_T_323,
      &_decoded_T_325,
      &_decoded_T_329,
      &_decoded_T_331,
      &_decoded_T_333,
      &_decoded_T_339,
      &_decoded_T_343,
      &_decoded_T_347,
      &_decoded_T_351,
      &_decoded_T_359,
      &_decoded_T_363,
      &_decoded_T_365,
      &_decoded_T_379,
      &_decoded_T_387};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_3_vc_sel_2_4 =
    |{&_decoded_T_275,
      &_decoded_T_277,
      &_decoded_T_281,
      &_decoded_T_283,
      &_decoded_T_287,
      &_decoded_T_291,
      &_decoded_T_295,
      &_decoded_T_299,
      &_decoded_T_301,
      &_decoded_T_305,
      &_decoded_T_307,
      &_decoded_T_309,
      &_decoded_T_315,
      &_decoded_T_319,
      &_decoded_T_323,
      &_decoded_T_325,
      &_decoded_T_329,
      &_decoded_T_331,
      &_decoded_T_333,
      &_decoded_T_339,
      &_decoded_T_343,
      &_decoded_T_347,
      &_decoded_T_351,
      &_decoded_T_359,
      &_decoded_T_363,
      &_decoded_T_365,
      &_decoded_T_379,
      &_decoded_T_387};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_3_vc_sel_1_1 =
    |{&_decoded_T_279,
      &_decoded_T_285,
      &_decoded_T_289,
      &_decoded_T_293,
      &_decoded_T_297,
      &_decoded_T_303,
      &_decoded_T_311,
      &_decoded_T_313,
      &_decoded_T_317,
      &_decoded_T_321,
      &_decoded_T_357,
      &_decoded_T_373,
      &_decoded_T_377,
      &_decoded_T_385,
      &_decoded_T_393};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_3_vc_sel_1_2 =
    |{&_decoded_T_279,
      &_decoded_T_285,
      &_decoded_T_289,
      &_decoded_T_293,
      &_decoded_T_297,
      &_decoded_T_303,
      &_decoded_T_311,
      &_decoded_T_313,
      &_decoded_T_317,
      &_decoded_T_321,
      &_decoded_T_357,
      &_decoded_T_373,
      &_decoded_T_377,
      &_decoded_T_385,
      &_decoded_T_393};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_3_vc_sel_1_3 =
    |{&_decoded_T_279,
      &_decoded_T_285,
      &_decoded_T_289,
      &_decoded_T_293,
      &_decoded_T_297,
      &_decoded_T_303,
      &_decoded_T_311,
      &_decoded_T_313,
      &_decoded_T_317,
      &_decoded_T_321,
      &_decoded_T_327,
      &_decoded_T_335,
      &_decoded_T_337,
      &_decoded_T_341,
      &_decoded_T_345,
      &_decoded_T_355,
      &_decoded_T_371,
      &_decoded_T_375,
      &_decoded_T_383,
      &_decoded_T_391};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_3_vc_sel_1_4 =
    |{&_decoded_T_279,
      &_decoded_T_285,
      &_decoded_T_289,
      &_decoded_T_293,
      &_decoded_T_297,
      &_decoded_T_303,
      &_decoded_T_311,
      &_decoded_T_313,
      &_decoded_T_317,
      &_decoded_T_321,
      &_decoded_T_327,
      &_decoded_T_335,
      &_decoded_T_337,
      &_decoded_T_341,
      &_decoded_T_345,
      &_decoded_T_355,
      &_decoded_T_371,
      &_decoded_T_375,
      &_decoded_T_383,
      &_decoded_T_391};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_2_vc_sel_3_0 = &_decoded_T_203;	// Cat.scala:33:92, pla.scala:98:74
  assign io_resp_2_vc_sel_3_1 =
    |{&_decoded_T_203,
      &_decoded_T_207,
      &{io_req_2_bits_flow_egress_node[0], _GEN_0[7], io_req_2_bits_src_virt_id[1]},
      &{io_req_2_bits_flow_egress_node[0], _GEN_0[7], io_req_2_bits_src_virt_id[2]}};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29, :98:74, :114:39
  assign io_resp_2_vc_sel_3_2 =
    |{&_decoded_T_203, &_decoded_T_207, &_decoded_T_213, &_decoded_T_223};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_2_vc_sel_3_3 =
    |{&_decoded_T_203, &_decoded_T_207, &_decoded_T_213, &_decoded_T_223};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_2_vc_sel_3_4 =
    |{&_decoded_T_203,
      &_decoded_T_207,
      &_decoded_T_213,
      &{io_req_2_bits_flow_egress_node[0], io_req_2_bits_src_virt_id[2]}};	// Cat.scala:33:92, pla.scala:90:45, :98:74, :114:39
  assign io_resp_2_vc_sel_1_1 = |{&_decoded_T_205, &_decoded_T_209, &_decoded_T_217};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_2_vc_sel_1_2 = |{&_decoded_T_205, &_decoded_T_209, &_decoded_T_217};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_2_vc_sel_1_3 = |{&_decoded_T_205, &_decoded_T_209, &_decoded_T_217};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_2_vc_sel_1_4 = |{&_decoded_T_205, &_decoded_T_209, &_decoded_T_217};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_2_vc_sel_0_4 = &{_GEN_0[0], _GEN_0[2], io_req_2_bits_src_virt_id[2]};	// Cat.scala:33:92, pla.scala:78:21, :90:45, :91:29, :98:74
  assign io_resp_1_vc_sel_0_4 = io_req_1_bits_src_virt_id[2];	// pla.scala:90:45
  assign io_resp_0_vc_sel_3_1 =
    |{&_decoded_T_6,
      &_decoded_T_14,
      &_decoded_T_20,
      &_decoded_T_26,
      &_decoded_T_32,
      &_decoded_T_40,
      &_decoded_T_50,
      &_decoded_T_54,
      &_decoded_T_60,
      &_decoded_T_66,
      &_decoded_T_74,
      &_decoded_T_84,
      &_decoded_T_88,
      &_decoded_T_94,
      &_decoded_T_100};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_3_2 =
    |{&_decoded_T_6,
      &_decoded_T_14,
      &_decoded_T_20,
      &_decoded_T_26,
      &_decoded_T_32,
      &_decoded_T_40,
      &_decoded_T_50,
      &_decoded_T_54,
      &_decoded_T_60,
      &_decoded_T_66,
      &_decoded_T_74,
      &_decoded_T_84,
      &_decoded_T_88,
      &_decoded_T_94,
      &_decoded_T_100};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_3_3 =
    |{&_decoded_T_6,
      &_decoded_T_14,
      &_decoded_T_20,
      &_decoded_T_26,
      &_decoded_T_32,
      &_decoded_T_40,
      &_decoded_T_50,
      &_decoded_T_54,
      &_decoded_T_60,
      &_decoded_T_66,
      &_decoded_T_74,
      &_decoded_T_84,
      &_decoded_T_88,
      &_decoded_T_94,
      &_decoded_T_100};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_3_4 =
    |{&_decoded_T_6,
      &_decoded_T_14,
      &_decoded_T_20,
      &_decoded_T_26,
      &_decoded_T_32,
      &_decoded_T_40,
      &_decoded_T_50,
      &_decoded_T_54,
      &_decoded_T_60,
      &_decoded_T_66,
      &_decoded_T_74,
      &_decoded_T_84,
      &_decoded_T_88,
      &_decoded_T_94,
      &_decoded_T_100};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_2_1 =
    |{&_decoded_T,
      &_decoded_T_2,
      &_decoded_T_8,
      &_decoded_T_10,
      &_decoded_T_16,
      &_decoded_T_22,
      &_decoded_T_28,
      &_decoded_T_34,
      &_decoded_T_36,
      &_decoded_T_42,
      &_decoded_T_44,
      &_decoded_T_46,
      &_decoded_T_56,
      &_decoded_T_62,
      &_decoded_T_68,
      &_decoded_T_70,
      &_decoded_T_76,
      &_decoded_T_78,
      &_decoded_T_80,
      &_decoded_T_90,
      &_decoded_T_96};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_2_2 =
    |{&_decoded_T,
      &_decoded_T_2,
      &_decoded_T_8,
      &_decoded_T_10,
      &_decoded_T_16,
      &_decoded_T_22,
      &_decoded_T_28,
      &_decoded_T_34,
      &_decoded_T_36,
      &_decoded_T_42,
      &_decoded_T_44,
      &_decoded_T_46,
      &_decoded_T_56,
      &_decoded_T_62,
      &_decoded_T_68,
      &_decoded_T_70,
      &_decoded_T_76,
      &_decoded_T_78,
      &_decoded_T_80,
      &_decoded_T_90,
      &_decoded_T_96};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_2_3 =
    |{&_decoded_T,
      &_decoded_T_2,
      &_decoded_T_8,
      &_decoded_T_10,
      &_decoded_T_16,
      &_decoded_T_22,
      &_decoded_T_28,
      &_decoded_T_34,
      &_decoded_T_36,
      &_decoded_T_42,
      &_decoded_T_44,
      &_decoded_T_46,
      &_decoded_T_56,
      &_decoded_T_62,
      &_decoded_T_68,
      &_decoded_T_70,
      &_decoded_T_76,
      &_decoded_T_78,
      &_decoded_T_80,
      &_decoded_T_90,
      &_decoded_T_96};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_2_4 =
    |{&_decoded_T,
      &_decoded_T_2,
      &_decoded_T_8,
      &_decoded_T_10,
      &_decoded_T_16,
      &_decoded_T_22,
      &_decoded_T_28,
      &_decoded_T_34,
      &_decoded_T_36,
      &_decoded_T_42,
      &_decoded_T_44,
      &_decoded_T_46,
      &_decoded_T_56,
      &_decoded_T_62,
      &_decoded_T_68,
      &_decoded_T_70,
      &_decoded_T_76,
      &_decoded_T_78,
      &_decoded_T_80,
      &_decoded_T_90,
      &_decoded_T_96};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_1_1 =
    |{&_decoded_T_4,
      &_decoded_T_12,
      &_decoded_T_18,
      &_decoded_T_24,
      &_decoded_T_30,
      &_decoded_T_38,
      &_decoded_T_48,
      &_decoded_T_52,
      &_decoded_T_58,
      &_decoded_T_64,
      &_decoded_T_72,
      &_decoded_T_82,
      &_decoded_T_86,
      &_decoded_T_92,
      &_decoded_T_98};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_1_2 =
    |{&_decoded_T_4,
      &_decoded_T_12,
      &_decoded_T_18,
      &_decoded_T_24,
      &_decoded_T_30,
      &_decoded_T_38,
      &_decoded_T_48,
      &_decoded_T_52,
      &_decoded_T_58,
      &_decoded_T_64,
      &_decoded_T_72,
      &_decoded_T_82,
      &_decoded_T_86,
      &_decoded_T_92,
      &_decoded_T_98};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_1_3 =
    |{&_decoded_T_4,
      &_decoded_T_12,
      &_decoded_T_18,
      &_decoded_T_24,
      &_decoded_T_30,
      &_decoded_T_38,
      &_decoded_T_48,
      &_decoded_T_52,
      &_decoded_T_58,
      &_decoded_T_64,
      &_decoded_T_72,
      &_decoded_T_82,
      &_decoded_T_86,
      &_decoded_T_92,
      &_decoded_T_98};	// Cat.scala:33:92, pla.scala:98:74, :114:39
  assign io_resp_0_vc_sel_1_4 =
    |{&_decoded_T_4,
      &_decoded_T_12,
      &_decoded_T_18,
      &_decoded_T_24,
      &_decoded_T_30,
      &_decoded_T_38,
      &_decoded_T_48,
      &_decoded_T_52,
      &_decoded_T_58,
      &_decoded_T_64,
      &_decoded_T_72,
      &_decoded_T_82,
      &_decoded_T_86,
      &_decoded_T_92,
      &_decoded_T_98};	// Cat.scala:33:92, pla.scala:98:74, :114:39
endmodule

