
EVAL_DIR := ../../../

BENCH := montecarlo

VERILOG_SOURCES := $(EVAL_DIR)/workloads/src/montecarlo/Main.sv \
				   $(EVAL_DIR)/workloads/src/montecarlo/MonteCarloAccelerator.sv


# PLUS_ARGS := +CYCLES=4000000

COMMON_FLAGS := -Wno-WIDTH

include ../../common/rules.mk
