// Generated by CIRCT firtool-1.30.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module BundleBridgeNexus_555(
  output [5:0] auto_out_60,
               auto_out_59,
               auto_out_58,
               auto_out_57,
               auto_out_56,
               auto_out_55,
               auto_out_54,
               auto_out_53,
               auto_out_52,
               auto_out_51,
               auto_out_50,
               auto_out_49,
               auto_out_48,
               auto_out_47,
               auto_out_46,
               auto_out_45,
               auto_out_44,
               auto_out_43,
               auto_out_42,
               auto_out_41,
               auto_out_40,
               auto_out_39,
               auto_out_38,
               auto_out_37,
               auto_out_36,
               auto_out_35,
               auto_out_34,
               auto_out_33,
               auto_out_32,
               auto_out_31,
               auto_out_30,
               auto_out_29,
               auto_out_28,
               auto_out_27,
               auto_out_26,
               auto_out_25,
               auto_out_24,
               auto_out_23,
               auto_out_22,
               auto_out_21,
               auto_out_20,
               auto_out_19,
               auto_out_18,
               auto_out_17,
               auto_out_16,
               auto_out_15,
               auto_out_14,
               auto_out_13,
               auto_out_12,
               auto_out_11,
               auto_out_10,
               auto_out_9,
               auto_out_8,
               auto_out_7,
               auto_out_6,
               auto_out_5,
               auto_out_4,
               auto_out_3,
               auto_out_2,
               auto_out_1,
               auto_out_0
);

  wire [5:0] outputs_0 = 6'h0;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_1 = 6'h1;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_2 = 6'h2;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_3 = 6'h3;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_4 = 6'h4;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_5 = 6'h5;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_6 = 6'h6;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_7 = 6'h7;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_8 = 6'h8;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_9 = 6'h9;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_10 = 6'hA;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_11 = 6'hB;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_12 = 6'hC;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_13 = 6'hD;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_14 = 6'hE;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_15 = 6'hF;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_16 = 6'h10;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_17 = 6'h11;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_18 = 6'h12;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_19 = 6'h13;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_20 = 6'h14;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_21 = 6'h15;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_22 = 6'h16;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_23 = 6'h17;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_24 = 6'h18;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_25 = 6'h19;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_26 = 6'h1A;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_27 = 6'h1B;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_28 = 6'h1C;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_29 = 6'h1D;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_30 = 6'h1E;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_31 = 6'h1F;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_32 = 6'h20;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_33 = 6'h21;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_34 = 6'h22;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_35 = 6'h23;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_36 = 6'h24;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_37 = 6'h25;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_38 = 6'h26;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_39 = 6'h27;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_40 = 6'h28;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_41 = 6'h29;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_42 = 6'h2A;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_43 = 6'h2B;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_44 = 6'h2C;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_45 = 6'h2D;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_46 = 6'h2E;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_47 = 6'h2F;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_48 = 6'h30;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_49 = 6'h31;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_50 = 6'h32;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_51 = 6'h33;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_52 = 6'h34;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_53 = 6'h35;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_54 = 6'h36;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_55 = 6'h37;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_56 = 6'h38;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_57 = 6'h39;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_58 = 6'h3A;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_59 = 6'h3B;	// @[HasTiles.scala:159:32]
  wire [5:0] outputs_60 = 6'h3C;	// @[HasTiles.scala:159:32]
  assign auto_out_60 = outputs_60;	// @[HasTiles.scala:159:32]
  assign auto_out_59 = outputs_59;	// @[HasTiles.scala:159:32]
  assign auto_out_58 = outputs_58;	// @[HasTiles.scala:159:32]
  assign auto_out_57 = outputs_57;	// @[HasTiles.scala:159:32]
  assign auto_out_56 = outputs_56;	// @[HasTiles.scala:159:32]
  assign auto_out_55 = outputs_55;	// @[HasTiles.scala:159:32]
  assign auto_out_54 = outputs_54;	// @[HasTiles.scala:159:32]
  assign auto_out_53 = outputs_53;	// @[HasTiles.scala:159:32]
  assign auto_out_52 = outputs_52;	// @[HasTiles.scala:159:32]
  assign auto_out_51 = outputs_51;	// @[HasTiles.scala:159:32]
  assign auto_out_50 = outputs_50;	// @[HasTiles.scala:159:32]
  assign auto_out_49 = outputs_49;	// @[HasTiles.scala:159:32]
  assign auto_out_48 = outputs_48;	// @[HasTiles.scala:159:32]
  assign auto_out_47 = outputs_47;	// @[HasTiles.scala:159:32]
  assign auto_out_46 = outputs_46;	// @[HasTiles.scala:159:32]
  assign auto_out_45 = outputs_45;	// @[HasTiles.scala:159:32]
  assign auto_out_44 = outputs_44;	// @[HasTiles.scala:159:32]
  assign auto_out_43 = outputs_43;	// @[HasTiles.scala:159:32]
  assign auto_out_42 = outputs_42;	// @[HasTiles.scala:159:32]
  assign auto_out_41 = outputs_41;	// @[HasTiles.scala:159:32]
  assign auto_out_40 = outputs_40;	// @[HasTiles.scala:159:32]
  assign auto_out_39 = outputs_39;	// @[HasTiles.scala:159:32]
  assign auto_out_38 = outputs_38;	// @[HasTiles.scala:159:32]
  assign auto_out_37 = outputs_37;	// @[HasTiles.scala:159:32]
  assign auto_out_36 = outputs_36;	// @[HasTiles.scala:159:32]
  assign auto_out_35 = outputs_35;	// @[HasTiles.scala:159:32]
  assign auto_out_34 = outputs_34;	// @[HasTiles.scala:159:32]
  assign auto_out_33 = outputs_33;	// @[HasTiles.scala:159:32]
  assign auto_out_32 = outputs_32;	// @[HasTiles.scala:159:32]
  assign auto_out_31 = outputs_31;	// @[HasTiles.scala:159:32]
  assign auto_out_30 = outputs_30;	// @[HasTiles.scala:159:32]
  assign auto_out_29 = outputs_29;	// @[HasTiles.scala:159:32]
  assign auto_out_28 = outputs_28;	// @[HasTiles.scala:159:32]
  assign auto_out_27 = outputs_27;	// @[HasTiles.scala:159:32]
  assign auto_out_26 = outputs_26;	// @[HasTiles.scala:159:32]
  assign auto_out_25 = outputs_25;	// @[HasTiles.scala:159:32]
  assign auto_out_24 = outputs_24;	// @[HasTiles.scala:159:32]
  assign auto_out_23 = outputs_23;	// @[HasTiles.scala:159:32]
  assign auto_out_22 = outputs_22;	// @[HasTiles.scala:159:32]
  assign auto_out_21 = outputs_21;	// @[HasTiles.scala:159:32]
  assign auto_out_20 = outputs_20;	// @[HasTiles.scala:159:32]
  assign auto_out_19 = outputs_19;	// @[HasTiles.scala:159:32]
  assign auto_out_18 = outputs_18;	// @[HasTiles.scala:159:32]
  assign auto_out_17 = outputs_17;	// @[HasTiles.scala:159:32]
  assign auto_out_16 = outputs_16;	// @[HasTiles.scala:159:32]
  assign auto_out_15 = outputs_15;	// @[HasTiles.scala:159:32]
  assign auto_out_14 = outputs_14;	// @[HasTiles.scala:159:32]
  assign auto_out_13 = outputs_13;	// @[HasTiles.scala:159:32]
  assign auto_out_12 = outputs_12;	// @[HasTiles.scala:159:32]
  assign auto_out_11 = outputs_11;	// @[HasTiles.scala:159:32]
  assign auto_out_10 = outputs_10;	// @[HasTiles.scala:159:32]
  assign auto_out_9 = outputs_9;	// @[HasTiles.scala:159:32]
  assign auto_out_8 = outputs_8;	// @[HasTiles.scala:159:32]
  assign auto_out_7 = outputs_7;	// @[HasTiles.scala:159:32]
  assign auto_out_6 = outputs_6;	// @[HasTiles.scala:159:32]
  assign auto_out_5 = outputs_5;	// @[HasTiles.scala:159:32]
  assign auto_out_4 = outputs_4;	// @[HasTiles.scala:159:32]
  assign auto_out_3 = outputs_3;	// @[HasTiles.scala:159:32]
  assign auto_out_2 = outputs_2;	// @[HasTiles.scala:159:32]
  assign auto_out_1 = outputs_1;	// @[HasTiles.scala:159:32]
  assign auto_out_0 = outputs_0;	// @[HasTiles.scala:159:32]
endmodule

