// Generated by CIRCT firtool-1.30.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module IngressUnit_235(
  input         clock,
                reset,
                io_vcalloc_req_ready,
                io_vcalloc_resp_vc_sel_3_0,
                io_vcalloc_resp_vc_sel_2_0,
                io_vcalloc_resp_vc_sel_1_0,
                io_vcalloc_resp_vc_sel_0_0,
                io_vcalloc_resp_vc_sel_0_1,
                io_vcalloc_resp_vc_sel_0_2,
                io_vcalloc_resp_vc_sel_0_3,
                io_vcalloc_resp_vc_sel_0_4,
                io_out_credit_available_3_0,
                io_out_credit_available_2_0,
                io_out_credit_available_1_0,
                io_out_credit_available_0_1,
                io_out_credit_available_0_2,
                io_out_credit_available_0_3,
                io_out_credit_available_0_4,
                io_salloc_req_0_ready,
                io_in_valid,
                io_in_bits_head,
                io_in_bits_tail,
  input  [72:0] io_in_bits_payload,
  input  [7:0]  io_in_bits_egress_id,
  output        io_vcalloc_req_valid,
                io_vcalloc_req_bits_vc_sel_3_0,
                io_vcalloc_req_bits_vc_sel_2_0,
                io_vcalloc_req_bits_vc_sel_1_0,
                io_vcalloc_req_bits_vc_sel_0_0,
                io_vcalloc_req_bits_vc_sel_0_1,
                io_vcalloc_req_bits_vc_sel_0_2,
                io_vcalloc_req_bits_vc_sel_0_3,
                io_vcalloc_req_bits_vc_sel_0_4,
                io_salloc_req_0_valid,
                io_salloc_req_0_bits_vc_sel_3_0,
                io_salloc_req_0_bits_vc_sel_2_0,
                io_salloc_req_0_bits_vc_sel_1_0,
                io_salloc_req_0_bits_vc_sel_0_0,
                io_salloc_req_0_bits_vc_sel_0_1,
                io_salloc_req_0_bits_vc_sel_0_2,
                io_salloc_req_0_bits_vc_sel_0_3,
                io_salloc_req_0_bits_vc_sel_0_4,
                io_salloc_req_0_bits_tail,
                io_out_0_valid,
                io_out_0_bits_flit_head,
                io_out_0_bits_flit_tail,
  output [72:0] io_out_0_bits_flit_payload,
  output [2:0]  io_out_0_bits_flit_flow_vnet_id,
  output [7:0]  io_out_0_bits_flit_flow_ingress_node,
  output [1:0]  io_out_0_bits_flit_flow_ingress_node_id,
  output [7:0]  io_out_0_bits_flit_flow_egress_node,
  output [1:0]  io_out_0_bits_flit_flow_egress_node_id,
  output [2:0]  io_out_0_bits_out_virt_channel,
  output        io_in_ready
);

  wire        _T_163;	// IngressUnit.scala:64:41
  wire        _vcalloc_q_io_enq_ready;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_valid;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_3_0;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_2_0;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_1_0;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_0_0;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_0_1;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_0_2;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_0_3;	// IngressUnit.scala:76:25
  wire        _vcalloc_q_io_deq_bits_vc_sel_0_4;	// IngressUnit.scala:76:25
  wire        _vcalloc_buffer_io_enq_ready;	// IngressUnit.scala:75:30
  wire        _vcalloc_buffer_io_deq_valid;	// IngressUnit.scala:75:30
  wire        _vcalloc_buffer_io_deq_bits_head;	// IngressUnit.scala:75:30
  wire        _vcalloc_buffer_io_deq_bits_tail;	// IngressUnit.scala:75:30
  wire [72:0] _vcalloc_buffer_io_deq_bits_payload;	// IngressUnit.scala:75:30
  wire [2:0]  _vcalloc_buffer_io_deq_bits_flow_vnet_id;	// IngressUnit.scala:75:30
  wire [7:0]  _vcalloc_buffer_io_deq_bits_flow_ingress_node;	// IngressUnit.scala:75:30
  wire [1:0]  _vcalloc_buffer_io_deq_bits_flow_ingress_node_id;	// IngressUnit.scala:75:30
  wire [7:0]  _vcalloc_buffer_io_deq_bits_flow_egress_node;	// IngressUnit.scala:75:30
  wire [1:0]  _vcalloc_buffer_io_deq_bits_flow_egress_node_id;	// IngressUnit.scala:75:30
  wire [2:0]  _vcalloc_buffer_io_deq_bits_virt_channel_id;	// IngressUnit.scala:75:30
  wire        _route_q_io_enq_ready;	// IngressUnit.scala:27:23
  wire        _route_q_io_deq_valid;	// IngressUnit.scala:27:23
  wire        _route_buffer_io_enq_ready;	// IngressUnit.scala:26:28
  wire        _route_buffer_io_deq_valid;	// IngressUnit.scala:26:28
  wire        _route_buffer_io_deq_bits_head;	// IngressUnit.scala:26:28
  wire        _route_buffer_io_deq_bits_tail;	// IngressUnit.scala:26:28
  wire [72:0] _route_buffer_io_deq_bits_payload;	// IngressUnit.scala:26:28
  wire [2:0]  _route_buffer_io_deq_bits_flow_vnet_id;	// IngressUnit.scala:26:28
  wire [7:0]  _route_buffer_io_deq_bits_flow_ingress_node;	// IngressUnit.scala:26:28
  wire [1:0]  _route_buffer_io_deq_bits_flow_ingress_node_id;	// IngressUnit.scala:26:28
  wire [7:0]  _route_buffer_io_deq_bits_flow_egress_node;	// IngressUnit.scala:26:28
  wire [1:0]  _route_buffer_io_deq_bits_flow_egress_node_id;	// IngressUnit.scala:26:28
  wire [2:0]  _route_buffer_io_deq_bits_virt_channel_id;	// IngressUnit.scala:26:28
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_78 =
    io_in_bits_egress_id == 8'h47;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_79 =
    io_in_bits_egress_id == 8'h91;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_80 =
    io_in_bits_egress_id == 8'h27;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_81 =
    io_in_bits_egress_id == 8'h73;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_82 =
    io_in_bits_egress_id == 8'hF;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_83 =
    io_in_bits_egress_id == 8'h57;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_84 =
    io_in_bits_egress_id == 8'h43;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_85 =
    io_in_bits_egress_id == 8'h6F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_86 =
    io_in_bits_egress_id == 8'h1F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_87 =
    io_in_bits_egress_id == 8'h15;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_88 =
    io_in_bits_egress_id == 8'h5D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_89 =
    io_in_bits_egress_id == 8'h3F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_90 =
    io_in_bits_egress_id == 8'h77;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_91 =
    io_in_bits_egress_id == 8'h8D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_92 =
    io_in_bits_egress_id == 8'h1;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_93 =
    io_in_bits_egress_id == 8'h6D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_94 =
    io_in_bits_egress_id == 8'h4B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_95 =
    io_in_bits_egress_id == 8'h19;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_96 =
    io_in_bits_egress_id == 8'h5F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_97 =
    io_in_bits_egress_id == 8'h67;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_98 =
    io_in_bits_egress_id == 8'h7B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_99 =
    io_in_bits_egress_id == 8'h3D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_100 =
    io_in_bits_egress_id == 8'h81;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_101 =
    io_in_bits_egress_id == 8'h1B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_102 =
    io_in_bits_egress_id == 8'h3;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_103 =
    io_in_bits_egress_id == 8'h9B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_104 =
    io_in_bits_egress_id == 8'h61;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_105 =
    io_in_bits_egress_id == 8'h65;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_106 =
    io_in_bits_egress_id == 8'h95;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_107 =
    io_in_bits_egress_id == 8'h41;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_108 =
    io_in_bits_egress_id == 8'h8F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_109 =
    io_in_bits_egress_id == 8'h5B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_110 =
    io_in_bits_egress_id == 8'h85;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_111 =
    io_in_bits_egress_id == 8'h13;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_112 =
    io_in_bits_egress_id == 8'h4D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_113 =
    io_in_bits_egress_id == 8'h5;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_114 =
    io_in_bits_egress_id == 8'h25;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_115 =
    io_in_bits_egress_id == 8'h23;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_116 =
    io_in_bits_egress_id == 8'h89;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_117 =
    io_in_bits_egress_id == 8'h35;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_118 =
    io_in_bits_egress_id == 8'h97;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_119 =
    io_in_bits_egress_id == 8'h79;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_120 =
    io_in_bits_egress_id == 8'h2B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_121 =
    io_in_bits_egress_id == 8'h49;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_122 =
    io_in_bits_egress_id == 8'h71;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_123 =
    io_in_bits_egress_id == 8'h3B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_124 =
    io_in_bits_egress_id == 8'h2F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_125 =
    io_in_bits_egress_id == 8'h37;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_126 =
    io_in_bits_egress_id == 8'h31;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_127 =
    io_in_bits_egress_id == 8'h33;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_128 =
    io_in_bits_egress_id == 8'h59;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_129 =
    io_in_bits_egress_id == 8'h21;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_130 =
    io_in_bits_egress_id == 8'h53;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_131 =
    io_in_bits_egress_id == 8'h11;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_132 =
    io_in_bits_egress_id == 8'h17;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_133 =
    io_in_bits_egress_id == 8'hB;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_134 =
    io_in_bits_egress_id == 8'h51;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_135 =
    io_in_bits_egress_id == 8'h9;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_136 =
    io_in_bits_egress_id == 8'h2D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_137 =
    io_in_bits_egress_id == 8'hD;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_138 =
    io_in_bits_egress_id == 8'h83;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_139 =
    io_in_bits_egress_id == 8'h63;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_140 =
    io_in_bits_egress_id == 8'h29;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_141 =
    io_in_bits_egress_id == 8'h7;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_142 =
    io_in_bits_egress_id == 8'h7D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_143 =
    io_in_bits_egress_id == 8'h99;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_144 =
    io_in_bits_egress_id == 8'h75;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_145 =
    io_in_bits_egress_id == 8'h55;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_146 =
    io_in_bits_egress_id == 8'h6B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_147 =
    io_in_bits_egress_id == 8'h45;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_148 =
    io_in_bits_egress_id == 8'h7F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_149 =
    io_in_bits_egress_id == 8'h8B;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_150 =
    io_in_bits_egress_id == 8'h1D;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_151 =
    io_in_bits_egress_id == 8'h39;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_152 =
    io_in_bits_egress_id == 8'h93;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_153 =
    io_in_bits_egress_id == 8'h87;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_154 =
    io_in_bits_egress_id == 8'h4F;	// IngressUnit.scala:30:72
  wire        _route_buffer_io_enq_bits_flow_egress_node_id_T_155 =
    io_in_bits_egress_id == 8'h69;	// IngressUnit.scala:30:72
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_78 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_78 ? 6'h23 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_81 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_81 ? 6'h39 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_83 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_83 ? 6'h2B : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_84 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_84 ? 6'h21 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_85 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_85 ? 6'h37 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _route_buffer_io_enq_bits_flow_egress_node_T_87 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_87 ? 4'hA : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_88 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_88 ? 6'h2E : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_90 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_90 ? 6'h3B : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_93 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_93 ? 6'h36 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_94 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_94 ? 6'h25 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _route_buffer_io_enq_bits_flow_egress_node_T_95 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_95 ? 4'hC : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_96 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_96 ? 6'h2F : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_97 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_97 ? 6'h33 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_98 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_98 ? 6'h3D : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _route_buffer_io_enq_bits_flow_egress_node_T_99 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_99 ? 5'h1E : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _route_buffer_io_enq_bits_flow_egress_node_T_101 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_101 ? 4'hD : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _GEN = _route_buffer_io_enq_bits_flow_egress_node_id_T_105 ? 5'h19 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_109 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_109 ? 6'h2D : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _route_buffer_io_enq_bits_flow_egress_node_T_111 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_111 ? 4'h9 : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _GEN_0 = _route_buffer_io_enq_bits_flow_egress_node_id_T_112 ? 5'h13 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _GEN_1 = _route_buffer_io_enq_bits_flow_egress_node_id_T_114 ? 4'h9 : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _route_buffer_io_enq_bits_flow_egress_node_T_115 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_115 ? 5'h11 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _GEN_2 = _route_buffer_io_enq_bits_flow_egress_node_id_T_117 ? 4'hD : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _route_buffer_io_enq_bits_flow_egress_node_T_120 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_120 ? 5'h15 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _GEN_3 = _route_buffer_io_enq_bits_flow_egress_node_id_T_121 ? 4'h9 : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _route_buffer_io_enq_bits_flow_egress_node_T_123 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_123 ? 5'h1D : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _route_buffer_io_enq_bits_flow_egress_node_T_124 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_124 ? 5'h17 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _route_buffer_io_enq_bits_flow_egress_node_T_125 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_125 ? 5'h1B : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _route_buffer_io_enq_bits_flow_egress_node_T_127 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_127 ? 5'h19 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _GEN_4 = _route_buffer_io_enq_bits_flow_egress_node_id_T_128 ? 4'hB : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_130 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_130 ? 6'h29 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _route_buffer_io_enq_bits_flow_egress_node_T_132 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_132 ? 4'hB : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [2:0]  _route_buffer_io_enq_bits_flow_egress_node_T_133 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_133 ? 3'h5 : 3'h0;	// IngressUnit.scala:30:72, :51:44, Mux.scala:27:73
  wire [2:0]  _GEN_5 = _route_buffer_io_enq_bits_flow_egress_node_id_T_134 ? 3'h5 : 3'h0;	// IngressUnit.scala:30:72, :51:44, Mux.scala:27:73
  wire [3:0]  _GEN_6 = _route_buffer_io_enq_bits_flow_egress_node_id_T_136 ? 4'hB : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_139 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_139 ? 6'h31 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [2:0]  _GEN_7 = _route_buffer_io_enq_bits_flow_egress_node_id_T_140 ? 3'h5 : 3'h0;	// IngressUnit.scala:30:72, :51:44, Mux.scala:27:73
  wire [4:0]  _GEN_8 = _route_buffer_io_enq_bits_flow_egress_node_id_T_144 ? 5'h1D : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _GEN_9 = _route_buffer_io_enq_bits_flow_egress_node_id_T_145 ? 5'h15 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_146 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_146 ? 6'h35 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _GEN_10 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_147 ? 5'h11 : 5'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [5:0]  _route_buffer_io_enq_bits_flow_egress_node_T_154 =
    _route_buffer_io_enq_bits_flow_egress_node_id_T_154 ? 6'h27 : 6'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [3:0]  _GEN_11 = _route_buffer_io_enq_bits_flow_egress_node_id_T_155 ? 4'hD : 4'h0;	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [4:0]  _GEN_12 =
    _route_buffer_io_enq_bits_flow_egress_node_T_78[4:0]
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_80 ? 5'h13 : 5'h0)
    | _route_buffer_io_enq_bits_flow_egress_node_T_81[4:0];	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [1:0]  _GEN_13 =
    _GEN_12[4:3] | _route_buffer_io_enq_bits_flow_egress_node_T_83[4:3]
    | _route_buffer_io_enq_bits_flow_egress_node_T_85[4:3];	// Mux.scala:27:73
  wire [2:0]  _GEN_14 =
    _GEN_12[2:0] | {3{_route_buffer_io_enq_bits_flow_egress_node_id_T_82}}
    | _route_buffer_io_enq_bits_flow_egress_node_T_83[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_84[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_85[2:0]
    | {3{_route_buffer_io_enq_bits_flow_egress_node_id_T_86}}
    | _route_buffer_io_enq_bits_flow_egress_node_T_87[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_88[2:0]
    | {3{_route_buffer_io_enq_bits_flow_egress_node_id_T_89}}
    | _route_buffer_io_enq_bits_flow_egress_node_T_90[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_93[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_94[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_95[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_96[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_97[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_98[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_99[2:0]
    | _route_buffer_io_enq_bits_flow_egress_node_T_101[2:0];	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire [1:0]  _GEN_15 =
    _GEN_14[2:1] | _GEN[1:0] | _route_buffer_io_enq_bits_flow_egress_node_T_109[2:1]
    | _GEN_0[1:0];	// Mux.scala:27:73
  wire [6:0]  _route_buffer_io_enq_bits_flow_egress_node_WIRE =
    (_route_buffer_io_enq_bits_flow_egress_node_id_T_79 ? 7'h48 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_91 ? 7'h46 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_103 ? 7'h4D : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_106 ? 7'h4A : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_108 ? 7'h47 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_110 ? 7'h42 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_116 ? 7'h44 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_118 ? 7'h4B : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_138 ? 7'h41 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_143 ? 7'h4C : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_149 ? 7'h45 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_152 ? 7'h49 : 7'h0)
    | (_route_buffer_io_enq_bits_flow_egress_node_id_T_153 ? 7'h43 : 7'h0)
    | {_route_buffer_io_enq_bits_flow_egress_node_id_T_100,
       _route_buffer_io_enq_bits_flow_egress_node_T_78[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_81[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_83[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_84[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_85[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_88[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_90[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_93[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_94[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_96[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_97[5]
         | _route_buffer_io_enq_bits_flow_egress_node_T_98[5]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_104 | _GEN[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_107
         | _route_buffer_io_enq_bits_flow_egress_node_T_109[5] | _GEN_0[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_119 | _GEN_3[3]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_122 | _GEN_4[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_130[5] | _GEN_5[2]
         | _route_buffer_io_enq_bits_flow_egress_node_T_139[5]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_142 | _GEN_8[4] | _GEN_9[4]
         | _route_buffer_io_enq_bits_flow_egress_node_T_146[5] | _GEN_10[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
         | _route_buffer_io_enq_bits_flow_egress_node_T_154[5] | _GEN_11[3],
       _GEN_13[1] | _route_buffer_io_enq_bits_flow_egress_node_id_T_89
         | _route_buffer_io_enq_bits_flow_egress_node_T_90[4]
         | _route_buffer_io_enq_bits_flow_egress_node_T_93[4]
         | _route_buffer_io_enq_bits_flow_egress_node_T_97[4]
         | _route_buffer_io_enq_bits_flow_egress_node_T_98[4]
         | _route_buffer_io_enq_bits_flow_egress_node_T_99[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_104 | _GEN[3] | _GEN_1[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_115[4] | _GEN_2[3]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_119
         | _route_buffer_io_enq_bits_flow_egress_node_T_120[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_122
         | _route_buffer_io_enq_bits_flow_egress_node_T_123[4]
         | _route_buffer_io_enq_bits_flow_egress_node_T_124[4]
         | _route_buffer_io_enq_bits_flow_egress_node_T_125[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_126
         | _route_buffer_io_enq_bits_flow_egress_node_T_127[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_129 | _GEN_6[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_139[4] | _GEN_7[2]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_142 | _GEN_8[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_146[4]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_151 | _GEN_11[2],
       _GEN_13[0] | _route_buffer_io_enq_bits_flow_egress_node_id_T_86
         | _route_buffer_io_enq_bits_flow_egress_node_T_87[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_88[3]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_89
         | _route_buffer_io_enq_bits_flow_egress_node_T_90[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_95[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_96[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_98[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_99[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_101[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_109[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_111[3] | _GEN_2[2]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_119
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_122
         | _route_buffer_io_enq_bits_flow_egress_node_T_123[3]
         | _route_buffer_io_enq_bits_flow_egress_node_T_125[3]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_126
         | _route_buffer_io_enq_bits_flow_egress_node_T_127[3] | _GEN_4[1]
         | _route_buffer_io_enq_bits_flow_egress_node_T_130[3]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_131
         | _route_buffer_io_enq_bits_flow_egress_node_T_132[3] | _GEN_5[0]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_142 | _GEN_8[2] | _GEN_9[2]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_150
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_151,
       _GEN_15[1] | _route_buffer_io_enq_bits_flow_egress_node_id_T_119
         | _route_buffer_io_enq_bits_flow_egress_node_T_120[2] | _GEN_3[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_123[2]
         | _route_buffer_io_enq_bits_flow_egress_node_T_124[2] | _GEN_4[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_133[2]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_135 | _GEN_6[1]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_137 | _GEN_7[0]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_142
         | _route_buffer_io_enq_bits_flow_egress_node_T_146[2]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_150
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_151
         | _route_buffer_io_enq_bits_flow_egress_node_T_154[2] | _GEN_11[0],
       _GEN_15[0] | _route_buffer_io_enq_bits_flow_egress_node_id_T_113 | _GEN_1[0]
         | _GEN_2[0] | _route_buffer_io_enq_bits_flow_egress_node_T_124[1]
         | _route_buffer_io_enq_bits_flow_egress_node_T_125[1]
         | _route_buffer_io_enq_bits_flow_egress_node_T_132[1] | _GEN_6[0]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_137
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_141
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_142 | _GEN_8[0] | _GEN_9[0]
         | _GEN_10[0] | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_150
         | _route_buffer_io_enq_bits_flow_egress_node_T_154[1],
       _GEN_14[0] | _route_buffer_io_enq_bits_flow_egress_node_id_T_102
         | _route_buffer_io_enq_bits_flow_egress_node_T_109[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_111[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_115[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_120[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_123[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_124[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_125[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_127[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_130[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_132[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_133[0]
         | _route_buffer_io_enq_bits_flow_egress_node_T_139[0]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_141
         | _route_buffer_io_enq_bits_flow_egress_node_T_146[0]
         | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
         | _route_buffer_io_enq_bits_flow_egress_node_T_154[0]};	// IngressUnit.scala:30:72, Mux.scala:27:73
  wire        at_dest = _route_buffer_io_enq_bits_flow_egress_node_WIRE == 7'h4E;	// IngressUnit.scala:55:59, Mux.scala:27:73
  assign _T_163 = _route_buffer_io_enq_ready & io_in_valid & io_in_bits_head & at_dest;	// IngressUnit.scala:26:28, :55:59, :64:41
  wire        _GEN_16 =
    _T_163 | io_in_valid & _route_buffer_io_enq_ready & io_in_bits_head & ~at_dest;	// IngressUnit.scala:26:28, :55:59, :58:{86,89}, :62:24, :64:{41,53}, :65:26
  wire        _io_vcalloc_req_valid_output =
    _route_buffer_io_deq_valid & _route_q_io_deq_valid & _route_buffer_io_deq_bits_head
    & _vcalloc_buffer_io_enq_ready & _vcalloc_q_io_enq_ready;	// IngressUnit.scala:26:28, :27:23, :75:30, :76:25, :92:41
  wire        _route_buffer_io_deq_ready_T_8 =
    _vcalloc_buffer_io_enq_ready
    & (_route_q_io_deq_valid | ~_route_buffer_io_deq_bits_head)
    & (io_vcalloc_req_ready | ~_route_buffer_io_deq_bits_head)
    & (_vcalloc_q_io_enq_ready | ~_route_buffer_io_deq_bits_head);	// IngressUnit.scala:26:28, :27:23, :75:30, :76:25, :88:30, :94:27, :95:{27,37}, :96:29
  wire        _vcalloc_q_io_enq_valid_T =
    io_vcalloc_req_ready & _io_vcalloc_req_valid_output;	// Decoupled.scala:51:35, IngressUnit.scala:92:41
  wire [7:0]  _c_T_2 =
    {_vcalloc_q_io_deq_bits_vc_sel_3_0,
     _vcalloc_q_io_deq_bits_vc_sel_2_0,
     _vcalloc_q_io_deq_bits_vc_sel_1_0,
     _vcalloc_q_io_deq_bits_vc_sel_0_4,
     _vcalloc_q_io_deq_bits_vc_sel_0_3,
     _vcalloc_q_io_deq_bits_vc_sel_0_2,
     _vcalloc_q_io_deq_bits_vc_sel_0_1,
     _vcalloc_q_io_deq_bits_vc_sel_0_0}
    & {io_out_credit_available_3_0,
       io_out_credit_available_2_0,
       io_out_credit_available_1_0,
       io_out_credit_available_0_4,
       io_out_credit_available_0_3,
       io_out_credit_available_0_2,
       io_out_credit_available_0_1,
       1'h1};	// IngressUnit.scala:76:25, :107:{41,48,74}
  wire        _vcalloc_buffer_io_deq_ready_T_1 =
    io_salloc_req_0_ready & _vcalloc_q_io_deq_valid & (|_c_T_2);	// IngressUnit.scala:76:25, :107:{48,82}, :110:83
  wire        _out_bundle_valid_T =
    _vcalloc_buffer_io_deq_ready_T_1 & _vcalloc_buffer_io_deq_valid;	// Decoupled.scala:51:35, IngressUnit.scala:75:30, :110:83
  reg         out_bundle_valid;	// IngressUnit.scala:116:8
  reg         out_bundle_bits_flit_head;	// IngressUnit.scala:116:8
  reg         out_bundle_bits_flit_tail;	// IngressUnit.scala:116:8
  reg  [72:0] out_bundle_bits_flit_payload;	// IngressUnit.scala:116:8
  reg  [2:0]  out_bundle_bits_flit_flow_vnet_id;	// IngressUnit.scala:116:8
  reg  [7:0]  out_bundle_bits_flit_flow_ingress_node;	// IngressUnit.scala:116:8
  reg  [1:0]  out_bundle_bits_flit_flow_ingress_node_id;	// IngressUnit.scala:116:8
  reg  [7:0]  out_bundle_bits_flit_flow_egress_node;	// IngressUnit.scala:116:8
  reg  [1:0]  out_bundle_bits_flit_flow_egress_node_id;	// IngressUnit.scala:116:8
  reg  [2:0]  out_bundle_bits_out_virt_channel;	// IngressUnit.scala:116:8
  always @(posedge clock) begin
    out_bundle_valid <= _out_bundle_valid_T;	// Decoupled.scala:51:35, IngressUnit.scala:116:8
    out_bundle_bits_flit_head <= _vcalloc_buffer_io_deq_bits_head;	// IngressUnit.scala:75:30, :116:8
    out_bundle_bits_flit_tail <= _vcalloc_buffer_io_deq_bits_tail;	// IngressUnit.scala:75:30, :116:8
    out_bundle_bits_flit_payload <= _vcalloc_buffer_io_deq_bits_payload;	// IngressUnit.scala:75:30, :116:8
    out_bundle_bits_flit_flow_vnet_id <= _vcalloc_buffer_io_deq_bits_flow_vnet_id;	// IngressUnit.scala:75:30, :116:8
    out_bundle_bits_flit_flow_ingress_node <=
      _vcalloc_buffer_io_deq_bits_flow_ingress_node;	// IngressUnit.scala:75:30, :116:8
    out_bundle_bits_flit_flow_ingress_node_id <=
      _vcalloc_buffer_io_deq_bits_flow_ingress_node_id;	// IngressUnit.scala:75:30, :116:8
    out_bundle_bits_flit_flow_egress_node <= _vcalloc_buffer_io_deq_bits_flow_egress_node;	// IngressUnit.scala:75:30, :116:8
    out_bundle_bits_flit_flow_egress_node_id <=
      _vcalloc_buffer_io_deq_bits_flow_egress_node_id;	// IngressUnit.scala:75:30, :116:8
    if (_vcalloc_q_io_deq_bits_vc_sel_0_0 | _vcalloc_q_io_deq_bits_vc_sel_0_1
        | _vcalloc_q_io_deq_bits_vc_sel_0_2 | _vcalloc_q_io_deq_bits_vc_sel_0_3
        | _vcalloc_q_io_deq_bits_vc_sel_0_4)	// IngressUnit.scala:76:25, :123:67
      out_bundle_bits_out_virt_channel <=
        {_vcalloc_q_io_deq_bits_vc_sel_0_4,
         |{_vcalloc_q_io_deq_bits_vc_sel_0_3, _vcalloc_q_io_deq_bits_vc_sel_0_2},
         _vcalloc_q_io_deq_bits_vc_sel_0_3 | _vcalloc_q_io_deq_bits_vc_sel_0_1};	// Cat.scala:33:92, IngressUnit.scala:76:25, :116:8, OneHot.scala:30:18, :32:{14,28}
    else	// IngressUnit.scala:123:67
      out_bundle_bits_out_virt_channel <= 3'h0;	// IngressUnit.scala:51:44, :116:8
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// IngressUnit.scala:30:9
      if (~reset & io_in_valid
          & ~(_route_buffer_io_enq_bits_flow_egress_node_id_T_78
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_79
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_80
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_81
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_82
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_83
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_84
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_85
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_86
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_87
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_88
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_89
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_90
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_91
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_92
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_93
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_94
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_95
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_96
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_97
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_98
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_99
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_100
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_101
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_102
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_103
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_104
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_105
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_106
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_107
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_108
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_109
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_110
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_111
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_112
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_113
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_114
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_115
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_116
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_117
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_118
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_119
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_120
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_121
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_122
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_123
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_124
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_125
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_126
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_127
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_128
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_129
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_130
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_131
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_132
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_133
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_134
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_135
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_136
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_137
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_138
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_139
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_140
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_141
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_142
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_143
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_144
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_145
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_146
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_147
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_149
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_150
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_151
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_152
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_153
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_154
              | _route_buffer_io_enq_bits_flow_egress_node_id_T_155)) begin	// IngressUnit.scala:30:{9,27,72}, package.scala:73:59
        if (`ASSERT_VERBOSE_COND_)	// IngressUnit.scala:30:9
          $error("Assertion failed\n    at IngressUnit.scala:30 assert(!(io.in.valid && !cParam.possibleFlows.toSeq.map(_.egressId.U === io.in.bits.egress_id).orR))\n");	// IngressUnit.scala:30:9
        if (`STOP_COND_)	// IngressUnit.scala:30:9
          $fatal;	// IngressUnit.scala:30:9
      end
      if (~reset & _GEN_16 & ~_route_q_io_enq_ready) begin	// IngressUnit.scala:27:23, :62:24, :64:53, :65:26, :73:{9,36}
        if (`ASSERT_VERBOSE_COND_)	// IngressUnit.scala:73:9
          $error("Assertion failed\n    at IngressUnit.scala:73 assert(!(route_q.io.enq.valid && !route_q.io.enq.ready))\n");	// IngressUnit.scala:73:9
        if (`STOP_COND_)	// IngressUnit.scala:73:9
          $fatal;	// IngressUnit.scala:73:9
      end
      if (~reset & _vcalloc_q_io_enq_valid_T & ~_vcalloc_q_io_enq_ready) begin	// Decoupled.scala:51:35, IngressUnit.scala:76:25, :102:{9,38}
        if (`ASSERT_VERBOSE_COND_)	// IngressUnit.scala:102:9
          $error("Assertion failed\n    at IngressUnit.scala:102 assert(!(vcalloc_q.io.enq.valid && !vcalloc_q.io.enq.ready))\n");	// IngressUnit.scala:102:9
        if (`STOP_COND_)	// IngressUnit.scala:102:9
          $fatal;	// IngressUnit.scala:102:9
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        out_bundle_valid = _RANDOM_0[0];	// IngressUnit.scala:116:8
        out_bundle_bits_flit_head = _RANDOM_0[1];	// IngressUnit.scala:116:8
        out_bundle_bits_flit_tail = _RANDOM_0[2];	// IngressUnit.scala:116:8
        out_bundle_bits_flit_payload = {_RANDOM_0[31:3], _RANDOM_1, _RANDOM_2[11:0]};	// IngressUnit.scala:116:8
        out_bundle_bits_flit_flow_vnet_id = _RANDOM_2[14:12];	// IngressUnit.scala:116:8
        out_bundle_bits_flit_flow_ingress_node = _RANDOM_2[22:15];	// IngressUnit.scala:116:8
        out_bundle_bits_flit_flow_ingress_node_id = _RANDOM_2[24:23];	// IngressUnit.scala:116:8
        out_bundle_bits_flit_flow_egress_node = {_RANDOM_2[31:25], _RANDOM_3[0]};	// IngressUnit.scala:116:8
        out_bundle_bits_flit_flow_egress_node_id = _RANDOM_3[2:1];	// IngressUnit.scala:116:8
        out_bundle_bits_out_virt_channel = _RANDOM_3[8:6];	// IngressUnit.scala:116:8
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  Queue_5 route_buffer (	// IngressUnit.scala:26:28
    .clock                            (clock),
    .reset                            (reset),
    .io_enq_valid                     (io_in_valid),
    .io_enq_bits_head                 (io_in_bits_head),
    .io_enq_bits_tail                 (io_in_bits_tail),
    .io_enq_bits_payload              (io_in_bits_payload),
    .io_enq_bits_flow_vnet_id         (3'h1),
    .io_enq_bits_flow_ingress_node    (8'h4E),
    .io_enq_bits_flow_ingress_node_id (2'h1),
    .io_enq_bits_flow_egress_node
      ({1'h0, _route_buffer_io_enq_bits_flow_egress_node_WIRE}),	// IngressUnit.scala:41:50, Mux.scala:27:73
    .io_enq_bits_flow_egress_node_id
      ({1'h0,
        _route_buffer_io_enq_bits_flow_egress_node_id_T_78
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_79
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_80
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_81
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_82
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_83
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_84
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_85
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_86
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_87
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_88
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_89
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_90
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_91
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_92
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_93
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_94
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_95
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_96
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_97
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_98
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_99
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_100
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_101
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_102
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_103
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_104
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_105
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_106
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_107
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_108
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_109
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_110
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_111
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_112
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_113
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_114
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_115
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_116
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_117
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_118
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_119
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_120
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_121
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_122
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_123
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_124
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_125
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_126
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_127
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_128
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_129
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_130
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_131
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_132
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_133
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_134
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_135
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_136
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_137
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_138
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_139
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_140
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_141
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_142
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_143
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_144
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_145
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_146
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_147
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_148
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_149
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_150
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_151
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_152
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_153
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_154
          | _route_buffer_io_enq_bits_flow_egress_node_id_T_155}),	// IngressUnit.scala:30:72, :45:50, Mux.scala:27:73
    .io_enq_bits_virt_channel_id      (3'h0),	// IngressUnit.scala:51:44
    .io_deq_ready                     (_route_buffer_io_deq_ready_T_8),	// IngressUnit.scala:95:37
    .io_enq_ready                     (_route_buffer_io_enq_ready),
    .io_deq_valid                     (_route_buffer_io_deq_valid),
    .io_deq_bits_head                 (_route_buffer_io_deq_bits_head),
    .io_deq_bits_tail                 (_route_buffer_io_deq_bits_tail),
    .io_deq_bits_payload              (_route_buffer_io_deq_bits_payload),
    .io_deq_bits_flow_vnet_id         (_route_buffer_io_deq_bits_flow_vnet_id),
    .io_deq_bits_flow_ingress_node    (_route_buffer_io_deq_bits_flow_ingress_node),
    .io_deq_bits_flow_ingress_node_id (_route_buffer_io_deq_bits_flow_ingress_node_id),
    .io_deq_bits_flow_egress_node     (_route_buffer_io_deq_bits_flow_egress_node),
    .io_deq_bits_flow_egress_node_id  (_route_buffer_io_deq_bits_flow_egress_node_id),
    .io_deq_bits_virt_channel_id      (_route_buffer_io_deq_bits_virt_channel_id)
  );
  Queue_1488 route_q (	// IngressUnit.scala:27:23
    .clock                  (clock),
    .reset                  (reset),
    .io_enq_valid           (_GEN_16),	// IngressUnit.scala:62:24, :64:53, :65:26
    .io_enq_bits_vc_sel_3_0 (_T_163 & io_in_bits_egress_id == 8'h9E),	// IngressUnit.scala:63:23, :64:{41,53}, :68:{40,66}
    .io_enq_bits_vc_sel_2_0 (_T_163 & io_in_bits_egress_id == 8'h9D),	// IngressUnit.scala:63:23, :64:{41,53}, :68:{40,66}
    .io_enq_bits_vc_sel_1_0 (_T_163 & io_in_bits_egress_id == 8'h9C),	// IngressUnit.scala:63:23, :64:{41,53}, :68:{40,66}
    .io_enq_bits_vc_sel_0_1 (~_T_163),	// IngressUnit.scala:63:23, :64:{41,53}, :66:52
    .io_enq_bits_vc_sel_0_2 (~_T_163),	// IngressUnit.scala:63:23, :64:{41,53}, :66:52
    .io_enq_bits_vc_sel_0_3 (~_T_163),	// IngressUnit.scala:63:23, :64:{41,53}, :66:52
    .io_enq_bits_vc_sel_0_4 (~_T_163),	// IngressUnit.scala:63:23, :64:{41,53}, :66:52
    .io_deq_ready
      (_route_buffer_io_deq_ready_T_8 & _route_buffer_io_deq_valid
       & _route_buffer_io_deq_bits_tail),	// IngressUnit.scala:26:28, :95:37, :97:55
    .io_enq_ready           (_route_q_io_enq_ready),
    .io_deq_valid           (_route_q_io_deq_valid),
    .io_deq_bits_vc_sel_3_0 (io_vcalloc_req_bits_vc_sel_3_0),
    .io_deq_bits_vc_sel_2_0 (io_vcalloc_req_bits_vc_sel_2_0),
    .io_deq_bits_vc_sel_1_0 (io_vcalloc_req_bits_vc_sel_1_0),
    .io_deq_bits_vc_sel_0_0 (io_vcalloc_req_bits_vc_sel_0_0),
    .io_deq_bits_vc_sel_0_1 (io_vcalloc_req_bits_vc_sel_0_1),
    .io_deq_bits_vc_sel_0_2 (io_vcalloc_req_bits_vc_sel_0_2),
    .io_deq_bits_vc_sel_0_3 (io_vcalloc_req_bits_vc_sel_0_3),
    .io_deq_bits_vc_sel_0_4 (io_vcalloc_req_bits_vc_sel_0_4)
  );
  Queue_5 vcalloc_buffer (	// IngressUnit.scala:75:30
    .clock                            (clock),
    .reset                            (reset),
    .io_enq_valid
      (_route_buffer_io_deq_valid
       & (_route_q_io_deq_valid | ~_route_buffer_io_deq_bits_head)
       & (io_vcalloc_req_ready | ~_route_buffer_io_deq_bits_head)),	// IngressUnit.scala:26:28, :27:23, :88:{27,30,37}, :89:27
    .io_enq_bits_head                 (_route_buffer_io_deq_bits_head),	// IngressUnit.scala:26:28
    .io_enq_bits_tail                 (_route_buffer_io_deq_bits_tail),	// IngressUnit.scala:26:28
    .io_enq_bits_payload              (_route_buffer_io_deq_bits_payload),	// IngressUnit.scala:26:28
    .io_enq_bits_flow_vnet_id         (_route_buffer_io_deq_bits_flow_vnet_id),	// IngressUnit.scala:26:28
    .io_enq_bits_flow_ingress_node    (_route_buffer_io_deq_bits_flow_ingress_node),	// IngressUnit.scala:26:28
    .io_enq_bits_flow_ingress_node_id (_route_buffer_io_deq_bits_flow_ingress_node_id),	// IngressUnit.scala:26:28
    .io_enq_bits_flow_egress_node     (_route_buffer_io_deq_bits_flow_egress_node),	// IngressUnit.scala:26:28
    .io_enq_bits_flow_egress_node_id  (_route_buffer_io_deq_bits_flow_egress_node_id),	// IngressUnit.scala:26:28
    .io_enq_bits_virt_channel_id      (_route_buffer_io_deq_bits_virt_channel_id),	// IngressUnit.scala:26:28
    .io_deq_ready                     (_vcalloc_buffer_io_deq_ready_T_1),	// IngressUnit.scala:110:83
    .io_enq_ready                     (_vcalloc_buffer_io_enq_ready),
    .io_deq_valid                     (_vcalloc_buffer_io_deq_valid),
    .io_deq_bits_head                 (_vcalloc_buffer_io_deq_bits_head),
    .io_deq_bits_tail                 (_vcalloc_buffer_io_deq_bits_tail),
    .io_deq_bits_payload              (_vcalloc_buffer_io_deq_bits_payload),
    .io_deq_bits_flow_vnet_id         (_vcalloc_buffer_io_deq_bits_flow_vnet_id),
    .io_deq_bits_flow_ingress_node    (_vcalloc_buffer_io_deq_bits_flow_ingress_node),
    .io_deq_bits_flow_ingress_node_id (_vcalloc_buffer_io_deq_bits_flow_ingress_node_id),
    .io_deq_bits_flow_egress_node     (_vcalloc_buffer_io_deq_bits_flow_egress_node),
    .io_deq_bits_flow_egress_node_id  (_vcalloc_buffer_io_deq_bits_flow_egress_node_id),
    .io_deq_bits_virt_channel_id      (_vcalloc_buffer_io_deq_bits_virt_channel_id)
  );
  Queue_1490 vcalloc_q (	// IngressUnit.scala:76:25
    .clock                  (clock),
    .reset                  (reset),
    .io_enq_valid           (_vcalloc_q_io_enq_valid_T),	// Decoupled.scala:51:35
    .io_enq_bits_vc_sel_3_0 (io_vcalloc_resp_vc_sel_3_0),
    .io_enq_bits_vc_sel_2_0 (io_vcalloc_resp_vc_sel_2_0),
    .io_enq_bits_vc_sel_1_0 (io_vcalloc_resp_vc_sel_1_0),
    .io_enq_bits_vc_sel_0_0 (io_vcalloc_resp_vc_sel_0_0),
    .io_enq_bits_vc_sel_0_1 (io_vcalloc_resp_vc_sel_0_1),
    .io_enq_bits_vc_sel_0_2 (io_vcalloc_resp_vc_sel_0_2),
    .io_enq_bits_vc_sel_0_3 (io_vcalloc_resp_vc_sel_0_3),
    .io_enq_bits_vc_sel_0_4 (io_vcalloc_resp_vc_sel_0_4),
    .io_deq_ready           (_vcalloc_buffer_io_deq_bits_tail & _out_bundle_valid_T),	// Decoupled.scala:51:35, IngressUnit.scala:75:30, :111:42
    .io_enq_ready           (_vcalloc_q_io_enq_ready),
    .io_deq_valid           (_vcalloc_q_io_deq_valid),
    .io_deq_bits_vc_sel_3_0 (_vcalloc_q_io_deq_bits_vc_sel_3_0),
    .io_deq_bits_vc_sel_2_0 (_vcalloc_q_io_deq_bits_vc_sel_2_0),
    .io_deq_bits_vc_sel_1_0 (_vcalloc_q_io_deq_bits_vc_sel_1_0),
    .io_deq_bits_vc_sel_0_0 (_vcalloc_q_io_deq_bits_vc_sel_0_0),
    .io_deq_bits_vc_sel_0_1 (_vcalloc_q_io_deq_bits_vc_sel_0_1),
    .io_deq_bits_vc_sel_0_2 (_vcalloc_q_io_deq_bits_vc_sel_0_2),
    .io_deq_bits_vc_sel_0_3 (_vcalloc_q_io_deq_bits_vc_sel_0_3),
    .io_deq_bits_vc_sel_0_4 (_vcalloc_q_io_deq_bits_vc_sel_0_4)
  );
  assign io_vcalloc_req_valid = _io_vcalloc_req_valid_output;	// IngressUnit.scala:92:41
  assign io_salloc_req_0_valid =
    _vcalloc_buffer_io_deq_valid & _vcalloc_q_io_deq_valid & (|_c_T_2);	// IngressUnit.scala:75:30, :76:25, :107:{48,82}, :109:83
  assign io_salloc_req_0_bits_vc_sel_3_0 = _vcalloc_q_io_deq_bits_vc_sel_3_0;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_vc_sel_2_0 = _vcalloc_q_io_deq_bits_vc_sel_2_0;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_vc_sel_1_0 = _vcalloc_q_io_deq_bits_vc_sel_1_0;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_vc_sel_0_0 = _vcalloc_q_io_deq_bits_vc_sel_0_0;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_vc_sel_0_1 = _vcalloc_q_io_deq_bits_vc_sel_0_1;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_vc_sel_0_2 = _vcalloc_q_io_deq_bits_vc_sel_0_2;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_vc_sel_0_3 = _vcalloc_q_io_deq_bits_vc_sel_0_3;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_vc_sel_0_4 = _vcalloc_q_io_deq_bits_vc_sel_0_4;	// IngressUnit.scala:76:25
  assign io_salloc_req_0_bits_tail = _vcalloc_buffer_io_deq_bits_tail;	// IngressUnit.scala:75:30
  assign io_out_0_valid = out_bundle_valid;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_head = out_bundle_bits_flit_head;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_tail = out_bundle_bits_flit_tail;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_payload = out_bundle_bits_flit_payload;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_flow_vnet_id = out_bundle_bits_flit_flow_vnet_id;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_flow_ingress_node = out_bundle_bits_flit_flow_ingress_node;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_flow_ingress_node_id =
    out_bundle_bits_flit_flow_ingress_node_id;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_flow_egress_node = out_bundle_bits_flit_flow_egress_node;	// IngressUnit.scala:116:8
  assign io_out_0_bits_flit_flow_egress_node_id =
    out_bundle_bits_flit_flow_egress_node_id;	// IngressUnit.scala:116:8
  assign io_out_0_bits_out_virt_channel = out_bundle_bits_out_virt_channel;	// IngressUnit.scala:116:8
  assign io_in_ready = _route_buffer_io_enq_ready;	// IngressUnit.scala:26:28
endmodule

