// Generated by CIRCT firtool-1.30.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module ProtocolNoC(
  input         clock,
                reset,
                io_protocol_0_in_0_a_valid,
  input  [2:0]  io_protocol_0_in_0_a_bits_opcode,
                io_protocol_0_in_0_a_bits_param,
  input  [3:0]  io_protocol_0_in_0_a_bits_size,
  input  [1:0]  io_protocol_0_in_0_a_bits_source,
  input  [31:0] io_protocol_0_in_0_a_bits_address,
  input  [7:0]  io_protocol_0_in_0_a_bits_mask,
  input  [63:0] io_protocol_0_in_0_a_bits_data,
  input         io_protocol_0_in_0_a_bits_corrupt,
                io_protocol_0_in_0_b_ready,
                io_protocol_0_in_0_c_valid,
  input  [2:0]  io_protocol_0_in_0_c_bits_opcode,
                io_protocol_0_in_0_c_bits_param,
  input  [3:0]  io_protocol_0_in_0_c_bits_size,
  input  [1:0]  io_protocol_0_in_0_c_bits_source,
  input  [31:0] io_protocol_0_in_0_c_bits_address,
  input  [63:0] io_protocol_0_in_0_c_bits_data,
  input         io_protocol_0_in_0_c_bits_corrupt,
                io_protocol_0_in_0_d_ready,
                io_protocol_0_in_0_e_valid,
  input  [2:0]  io_protocol_0_in_0_e_bits_sink,
  input         io_protocol_0_out_2_a_ready,
                io_protocol_0_out_2_d_valid,
  input  [2:0]  io_protocol_0_out_2_d_bits_opcode,
  input  [1:0]  io_protocol_0_out_2_d_bits_param,
  input  [2:0]  io_protocol_0_out_2_d_bits_size,
  input  [1:0]  io_protocol_0_out_2_d_bits_source,
  input         io_protocol_0_out_2_d_bits_sink,
                io_protocol_0_out_2_d_bits_denied,
  input  [63:0] io_protocol_0_out_2_d_bits_data,
  input         io_protocol_0_out_2_d_bits_corrupt,
                io_protocol_0_out_1_a_ready,
                io_protocol_0_out_1_b_valid,
  input  [1:0]  io_protocol_0_out_1_b_bits_param,
  input  [31:0] io_protocol_0_out_1_b_bits_address,
  input         io_protocol_0_out_1_c_ready,
                io_protocol_0_out_1_d_valid,
  input  [2:0]  io_protocol_0_out_1_d_bits_opcode,
  input  [1:0]  io_protocol_0_out_1_d_bits_param,
  input  [2:0]  io_protocol_0_out_1_d_bits_size,
  input  [1:0]  io_protocol_0_out_1_d_bits_source,
  input  [2:0]  io_protocol_0_out_1_d_bits_sink,
  input         io_protocol_0_out_1_d_bits_denied,
  input  [63:0] io_protocol_0_out_1_d_bits_data,
  input         io_protocol_0_out_1_d_bits_corrupt,
                io_protocol_0_out_0_a_ready,
                io_protocol_0_out_0_d_valid,
  input  [2:0]  io_protocol_0_out_0_d_bits_opcode,
  input  [1:0]  io_protocol_0_out_0_d_bits_param,
  input  [3:0]  io_protocol_0_out_0_d_bits_size,
  input  [1:0]  io_protocol_0_out_0_d_bits_source,
  input         io_protocol_0_out_0_d_bits_sink,
                io_protocol_0_out_0_d_bits_denied,
  input  [63:0] io_protocol_0_out_0_d_bits_data,
  input         io_protocol_0_out_0_d_bits_corrupt,
  output        io_protocol_0_in_0_a_ready,
                io_protocol_0_in_0_b_valid,
  output [2:0]  io_protocol_0_in_0_b_bits_opcode,
  output [1:0]  io_protocol_0_in_0_b_bits_param,
  output [3:0]  io_protocol_0_in_0_b_bits_size,
  output [1:0]  io_protocol_0_in_0_b_bits_source,
  output [31:0] io_protocol_0_in_0_b_bits_address,
  output [7:0]  io_protocol_0_in_0_b_bits_mask,
  output [63:0] io_protocol_0_in_0_b_bits_data,
  output        io_protocol_0_in_0_b_bits_corrupt,
                io_protocol_0_in_0_c_ready,
                io_protocol_0_in_0_d_valid,
  output [2:0]  io_protocol_0_in_0_d_bits_opcode,
  output [1:0]  io_protocol_0_in_0_d_bits_param,
  output [3:0]  io_protocol_0_in_0_d_bits_size,
  output [1:0]  io_protocol_0_in_0_d_bits_source,
  output [2:0]  io_protocol_0_in_0_d_bits_sink,
  output        io_protocol_0_in_0_d_bits_denied,
  output [63:0] io_protocol_0_in_0_d_bits_data,
  output        io_protocol_0_in_0_d_bits_corrupt,
                io_protocol_0_in_0_e_ready,
                io_protocol_0_out_2_a_valid,
  output [2:0]  io_protocol_0_out_2_a_bits_opcode,
                io_protocol_0_out_2_a_bits_param,
                io_protocol_0_out_2_a_bits_size,
  output [1:0]  io_protocol_0_out_2_a_bits_source,
  output [30:0] io_protocol_0_out_2_a_bits_address,
  output [7:0]  io_protocol_0_out_2_a_bits_mask,
  output [63:0] io_protocol_0_out_2_a_bits_data,
  output        io_protocol_0_out_2_a_bits_corrupt,
                io_protocol_0_out_2_d_ready,
                io_protocol_0_out_1_a_valid,
  output [2:0]  io_protocol_0_out_1_a_bits_opcode,
                io_protocol_0_out_1_a_bits_param,
                io_protocol_0_out_1_a_bits_size,
  output [1:0]  io_protocol_0_out_1_a_bits_source,
  output [31:0] io_protocol_0_out_1_a_bits_address,
  output [7:0]  io_protocol_0_out_1_a_bits_mask,
  output [63:0] io_protocol_0_out_1_a_bits_data,
  output        io_protocol_0_out_1_a_bits_corrupt,
                io_protocol_0_out_1_b_ready,
                io_protocol_0_out_1_c_valid,
  output [2:0]  io_protocol_0_out_1_c_bits_opcode,
                io_protocol_0_out_1_c_bits_param,
                io_protocol_0_out_1_c_bits_size,
  output [1:0]  io_protocol_0_out_1_c_bits_source,
  output [31:0] io_protocol_0_out_1_c_bits_address,
  output [63:0] io_protocol_0_out_1_c_bits_data,
  output        io_protocol_0_out_1_c_bits_corrupt,
                io_protocol_0_out_1_d_ready,
                io_protocol_0_out_1_e_valid,
  output [2:0]  io_protocol_0_out_1_e_bits_sink,
  output        io_protocol_0_out_0_a_valid,
  output [2:0]  io_protocol_0_out_0_a_bits_opcode,
                io_protocol_0_out_0_a_bits_param,
  output [3:0]  io_protocol_0_out_0_a_bits_size,
  output [1:0]  io_protocol_0_out_0_a_bits_source,
  output [25:0] io_protocol_0_out_0_a_bits_address,
  output [7:0]  io_protocol_0_out_0_a_bits_mask,
  output [63:0] io_protocol_0_out_0_a_bits_data,
  output        io_protocol_0_out_0_a_bits_corrupt,
                io_protocol_0_out_0_d_ready
);

  wire [3:0]  _nif_slave_2_io_tilelink_a_bits_size;	// Tilelink.scala:357:33
  wire [31:0] _nif_slave_2_io_tilelink_a_bits_address;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_a_ready;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_b_valid;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_b_bits_head;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_b_bits_tail;	// Tilelink.scala:357:33
  wire [72:0] _nif_slave_2_io_flits_b_bits_payload;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_c_ready;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_d_valid;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_d_bits_head;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_d_bits_tail;	// Tilelink.scala:357:33
  wire [72:0] _nif_slave_2_io_flits_d_bits_payload;	// Tilelink.scala:357:33
  wire        _nif_slave_2_io_flits_e_ready;	// Tilelink.scala:357:33
  wire [3:0]  _nif_slave_1_io_tilelink_a_bits_size;	// Tilelink.scala:357:33
  wire [3:0]  _nif_slave_1_io_tilelink_c_bits_size;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_a_ready;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_b_valid;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_b_bits_head;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_b_bits_tail;	// Tilelink.scala:357:33
  wire [72:0] _nif_slave_1_io_flits_b_bits_payload;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_c_ready;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_d_valid;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_d_bits_head;	// Tilelink.scala:357:33
  wire        _nif_slave_1_io_flits_d_bits_tail;	// Tilelink.scala:357:33
  wire [72:0] _nif_slave_1_io_flits_d_bits_payload;	// Tilelink.scala:357:33
  wire [31:0] _nif_slave_io_tilelink_a_bits_address;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_a_ready;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_b_valid;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_b_bits_head;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_b_bits_tail;	// Tilelink.scala:357:33
  wire [72:0] _nif_slave_io_flits_b_bits_payload;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_c_ready;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_d_valid;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_d_bits_head;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_d_bits_tail;	// Tilelink.scala:357:33
  wire [72:0] _nif_slave_io_flits_d_bits_payload;	// Tilelink.scala:357:33
  wire        _nif_slave_io_flits_e_ready;	// Tilelink.scala:357:33
  wire        _nif_master_io_flits_a_valid;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_a_bits_head;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_a_bits_tail;	// Tilelink.scala:330:34
  wire [72:0] _nif_master_io_flits_a_bits_payload;	// Tilelink.scala:330:34
  wire [3:0]  _nif_master_io_flits_a_bits_egress_id;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_b_ready;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_c_valid;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_c_bits_head;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_c_bits_tail;	// Tilelink.scala:330:34
  wire [72:0] _nif_master_io_flits_c_bits_payload;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_d_ready;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_e_valid;	// Tilelink.scala:330:34
  wire        _nif_master_io_flits_e_bits_head;	// Tilelink.scala:330:34
  wire [72:0] _nif_master_io_flits_e_bits_payload;	// Tilelink.scala:330:34
  wire        _noc_io_ingress_8_flit_ready;	// Protocol.scala:105:19
  wire        _noc_io_ingress_6_flit_ready;	// Protocol.scala:105:19
  wire        _noc_io_ingress_5_flit_ready;	// Protocol.scala:105:19
  wire        _noc_io_ingress_4_flit_ready;	// Protocol.scala:105:19
  wire        _noc_io_ingress_2_flit_ready;	// Protocol.scala:105:19
  wire        _noc_io_ingress_1_flit_ready;	// Protocol.scala:105:19
  wire        _noc_io_ingress_0_flit_ready;	// Protocol.scala:105:19
  wire        _noc_io_egress_10_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_10_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_10_flit_bits_tail;	// Protocol.scala:105:19
  wire        _noc_io_egress_9_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_9_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_9_flit_bits_tail;	// Protocol.scala:105:19
  wire        _noc_io_egress_8_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_8_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_8_flit_bits_tail;	// Protocol.scala:105:19
  wire [72:0] _noc_io_egress_8_flit_bits_payload;	// Protocol.scala:105:19
  wire        _noc_io_egress_7_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_7_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_7_flit_bits_tail;	// Protocol.scala:105:19
  wire [72:0] _noc_io_egress_7_flit_bits_payload;	// Protocol.scala:105:19
  wire        _noc_io_egress_6_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_6_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_6_flit_bits_tail;	// Protocol.scala:105:19
  wire [72:0] _noc_io_egress_6_flit_bits_payload;	// Protocol.scala:105:19
  wire        _noc_io_egress_5_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_5_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_5_flit_bits_tail;	// Protocol.scala:105:19
  wire [72:0] _noc_io_egress_5_flit_bits_payload;	// Protocol.scala:105:19
  wire        _noc_io_egress_4_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_4_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_4_flit_bits_tail;	// Protocol.scala:105:19
  wire        _noc_io_egress_3_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_3_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_3_flit_bits_tail;	// Protocol.scala:105:19
  wire        _noc_io_egress_2_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_2_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_2_flit_bits_tail;	// Protocol.scala:105:19
  wire [72:0] _noc_io_egress_2_flit_bits_payload;	// Protocol.scala:105:19
  wire        _noc_io_egress_1_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_1_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_1_flit_bits_tail;	// Protocol.scala:105:19
  wire [72:0] _noc_io_egress_1_flit_bits_payload;	// Protocol.scala:105:19
  wire        _noc_io_egress_0_flit_valid;	// Protocol.scala:105:19
  wire        _noc_io_egress_0_flit_bits_head;	// Protocol.scala:105:19
  wire        _noc_io_egress_0_flit_bits_tail;	// Protocol.scala:105:19
  wire [72:0] _noc_io_egress_0_flit_bits_payload;	// Protocol.scala:105:19
  NoC noc (	// Protocol.scala:105:19
    .clock                            (clock),
    .reset                            (reset),
    .io_ingress_8_flit_valid          (_nif_slave_2_io_flits_d_valid),	// Tilelink.scala:357:33
    .io_ingress_8_flit_bits_head      (_nif_slave_2_io_flits_d_bits_head),	// Tilelink.scala:357:33
    .io_ingress_8_flit_bits_tail      (_nif_slave_2_io_flits_d_bits_tail),	// Tilelink.scala:357:33
    .io_ingress_8_flit_bits_payload   (_nif_slave_2_io_flits_d_bits_payload),	// Tilelink.scala:357:33
    .io_ingress_7_flit_valid          (_nif_slave_2_io_flits_b_valid),	// Tilelink.scala:357:33
    .io_ingress_7_flit_bits_head      (_nif_slave_2_io_flits_b_bits_head),	// Tilelink.scala:357:33
    .io_ingress_7_flit_bits_tail      (_nif_slave_2_io_flits_b_bits_tail),	// Tilelink.scala:357:33
    .io_ingress_7_flit_bits_payload   (_nif_slave_2_io_flits_b_bits_payload),	// Tilelink.scala:357:33
    .io_ingress_6_flit_valid          (_nif_slave_1_io_flits_d_valid),	// Tilelink.scala:357:33
    .io_ingress_6_flit_bits_head      (_nif_slave_1_io_flits_d_bits_head),	// Tilelink.scala:357:33
    .io_ingress_6_flit_bits_tail      (_nif_slave_1_io_flits_d_bits_tail),	// Tilelink.scala:357:33
    .io_ingress_6_flit_bits_payload   (_nif_slave_1_io_flits_d_bits_payload),	// Tilelink.scala:357:33
    .io_ingress_5_flit_valid          (_nif_slave_1_io_flits_b_valid),	// Tilelink.scala:357:33
    .io_ingress_5_flit_bits_head      (_nif_slave_1_io_flits_b_bits_head),	// Tilelink.scala:357:33
    .io_ingress_5_flit_bits_tail      (_nif_slave_1_io_flits_b_bits_tail),	// Tilelink.scala:357:33
    .io_ingress_5_flit_bits_payload   (_nif_slave_1_io_flits_b_bits_payload),	// Tilelink.scala:357:33
    .io_ingress_4_flit_valid          (_nif_slave_io_flits_d_valid),	// Tilelink.scala:357:33
    .io_ingress_4_flit_bits_head      (_nif_slave_io_flits_d_bits_head),	// Tilelink.scala:357:33
    .io_ingress_4_flit_bits_tail      (_nif_slave_io_flits_d_bits_tail),	// Tilelink.scala:357:33
    .io_ingress_4_flit_bits_payload   (_nif_slave_io_flits_d_bits_payload),	// Tilelink.scala:357:33
    .io_ingress_3_flit_valid          (_nif_slave_io_flits_b_valid),	// Tilelink.scala:357:33
    .io_ingress_3_flit_bits_head      (_nif_slave_io_flits_b_bits_head),	// Tilelink.scala:357:33
    .io_ingress_3_flit_bits_tail      (_nif_slave_io_flits_b_bits_tail),	// Tilelink.scala:357:33
    .io_ingress_3_flit_bits_payload   (_nif_slave_io_flits_b_bits_payload),	// Tilelink.scala:357:33
    .io_ingress_2_flit_valid          (_nif_master_io_flits_e_valid),	// Tilelink.scala:330:34
    .io_ingress_2_flit_bits_head      (_nif_master_io_flits_e_bits_head),	// Tilelink.scala:330:34
    .io_ingress_2_flit_bits_payload   (_nif_master_io_flits_e_bits_payload),	// Tilelink.scala:330:34
    .io_ingress_1_flit_valid          (_nif_master_io_flits_c_valid),	// Tilelink.scala:330:34
    .io_ingress_1_flit_bits_head      (_nif_master_io_flits_c_bits_head),	// Tilelink.scala:330:34
    .io_ingress_1_flit_bits_tail      (_nif_master_io_flits_c_bits_tail),	// Tilelink.scala:330:34
    .io_ingress_1_flit_bits_payload   (_nif_master_io_flits_c_bits_payload),	// Tilelink.scala:330:34
    .io_ingress_0_flit_valid          (_nif_master_io_flits_a_valid),	// Tilelink.scala:330:34
    .io_ingress_0_flit_bits_head      (_nif_master_io_flits_a_bits_head),	// Tilelink.scala:330:34
    .io_ingress_0_flit_bits_tail      (_nif_master_io_flits_a_bits_tail),	// Tilelink.scala:330:34
    .io_ingress_0_flit_bits_payload   (_nif_master_io_flits_a_bits_payload),	// Tilelink.scala:330:34
    .io_ingress_0_flit_bits_egress_id (_nif_master_io_flits_a_bits_egress_id),	// Tilelink.scala:330:34
    .io_egress_10_flit_ready          (_nif_slave_2_io_flits_e_ready),	// Tilelink.scala:357:33
    .io_egress_9_flit_ready           (_nif_slave_2_io_flits_c_ready),	// Tilelink.scala:357:33
    .io_egress_8_flit_ready           (_nif_slave_2_io_flits_a_ready),	// Tilelink.scala:357:33
    .io_egress_6_flit_ready           (_nif_slave_1_io_flits_c_ready),	// Tilelink.scala:357:33
    .io_egress_5_flit_ready           (_nif_slave_1_io_flits_a_ready),	// Tilelink.scala:357:33
    .io_egress_4_flit_ready           (_nif_slave_io_flits_e_ready),	// Tilelink.scala:357:33
    .io_egress_3_flit_ready           (_nif_slave_io_flits_c_ready),	// Tilelink.scala:357:33
    .io_egress_2_flit_ready           (_nif_slave_io_flits_a_ready),	// Tilelink.scala:357:33
    .io_egress_1_flit_ready           (_nif_master_io_flits_d_ready),	// Tilelink.scala:330:34
    .io_egress_0_flit_ready           (_nif_master_io_flits_b_ready),	// Tilelink.scala:330:34
    .io_router_clocks_0_clock         (clock),
    .io_router_clocks_0_reset         (reset),
    .io_router_clocks_1_clock         (clock),
    .io_router_clocks_1_reset         (reset),
    .io_router_clocks_2_clock         (clock),
    .io_router_clocks_2_reset         (reset),
    .io_router_clocks_3_clock         (clock),
    .io_router_clocks_3_reset         (reset),
    .io_router_clocks_4_clock         (clock),
    .io_router_clocks_4_reset         (reset),
    .io_router_clocks_5_clock         (clock),
    .io_router_clocks_5_reset         (reset),
    .io_router_clocks_6_clock         (clock),
    .io_router_clocks_6_reset         (reset),
    .io_router_clocks_7_clock         (clock),
    .io_router_clocks_7_reset         (reset),
    .io_ingress_8_flit_ready          (_noc_io_ingress_8_flit_ready),
    .io_ingress_6_flit_ready          (_noc_io_ingress_6_flit_ready),
    .io_ingress_5_flit_ready          (_noc_io_ingress_5_flit_ready),
    .io_ingress_4_flit_ready          (_noc_io_ingress_4_flit_ready),
    .io_ingress_2_flit_ready          (_noc_io_ingress_2_flit_ready),
    .io_ingress_1_flit_ready          (_noc_io_ingress_1_flit_ready),
    .io_ingress_0_flit_ready          (_noc_io_ingress_0_flit_ready),
    .io_egress_10_flit_valid          (_noc_io_egress_10_flit_valid),
    .io_egress_10_flit_bits_head      (_noc_io_egress_10_flit_bits_head),
    .io_egress_10_flit_bits_tail      (_noc_io_egress_10_flit_bits_tail),
    .io_egress_9_flit_valid           (_noc_io_egress_9_flit_valid),
    .io_egress_9_flit_bits_head       (_noc_io_egress_9_flit_bits_head),
    .io_egress_9_flit_bits_tail       (_noc_io_egress_9_flit_bits_tail),
    .io_egress_8_flit_valid           (_noc_io_egress_8_flit_valid),
    .io_egress_8_flit_bits_head       (_noc_io_egress_8_flit_bits_head),
    .io_egress_8_flit_bits_tail       (_noc_io_egress_8_flit_bits_tail),
    .io_egress_8_flit_bits_payload    (_noc_io_egress_8_flit_bits_payload),
    .io_egress_7_flit_valid           (_noc_io_egress_7_flit_valid),
    .io_egress_7_flit_bits_head       (_noc_io_egress_7_flit_bits_head),
    .io_egress_7_flit_bits_tail       (_noc_io_egress_7_flit_bits_tail),
    .io_egress_7_flit_bits_payload    (_noc_io_egress_7_flit_bits_payload),
    .io_egress_6_flit_valid           (_noc_io_egress_6_flit_valid),
    .io_egress_6_flit_bits_head       (_noc_io_egress_6_flit_bits_head),
    .io_egress_6_flit_bits_tail       (_noc_io_egress_6_flit_bits_tail),
    .io_egress_6_flit_bits_payload    (_noc_io_egress_6_flit_bits_payload),
    .io_egress_5_flit_valid           (_noc_io_egress_5_flit_valid),
    .io_egress_5_flit_bits_head       (_noc_io_egress_5_flit_bits_head),
    .io_egress_5_flit_bits_tail       (_noc_io_egress_5_flit_bits_tail),
    .io_egress_5_flit_bits_payload    (_noc_io_egress_5_flit_bits_payload),
    .io_egress_4_flit_valid           (_noc_io_egress_4_flit_valid),
    .io_egress_4_flit_bits_head       (_noc_io_egress_4_flit_bits_head),
    .io_egress_4_flit_bits_tail       (_noc_io_egress_4_flit_bits_tail),
    .io_egress_3_flit_valid           (_noc_io_egress_3_flit_valid),
    .io_egress_3_flit_bits_head       (_noc_io_egress_3_flit_bits_head),
    .io_egress_3_flit_bits_tail       (_noc_io_egress_3_flit_bits_tail),
    .io_egress_2_flit_valid           (_noc_io_egress_2_flit_valid),
    .io_egress_2_flit_bits_head       (_noc_io_egress_2_flit_bits_head),
    .io_egress_2_flit_bits_tail       (_noc_io_egress_2_flit_bits_tail),
    .io_egress_2_flit_bits_payload    (_noc_io_egress_2_flit_bits_payload),
    .io_egress_1_flit_valid           (_noc_io_egress_1_flit_valid),
    .io_egress_1_flit_bits_head       (_noc_io_egress_1_flit_bits_head),
    .io_egress_1_flit_bits_tail       (_noc_io_egress_1_flit_bits_tail),
    .io_egress_1_flit_bits_payload    (_noc_io_egress_1_flit_bits_payload),
    .io_egress_0_flit_valid           (_noc_io_egress_0_flit_valid),
    .io_egress_0_flit_bits_head       (_noc_io_egress_0_flit_bits_head),
    .io_egress_0_flit_bits_tail       (_noc_io_egress_0_flit_bits_tail),
    .io_egress_0_flit_bits_payload    (_noc_io_egress_0_flit_bits_payload)
  );
  TLMasterToNoC nif_master (	// Tilelink.scala:330:34
    .clock                      (clock),
    .reset                      (reset),
    .io_tilelink_a_valid        (io_protocol_0_in_0_a_valid),
    .io_tilelink_a_bits_opcode  (io_protocol_0_in_0_a_bits_opcode),
    .io_tilelink_a_bits_param   (io_protocol_0_in_0_a_bits_param),
    .io_tilelink_a_bits_size    (io_protocol_0_in_0_a_bits_size),
    .io_tilelink_a_bits_source  (io_protocol_0_in_0_a_bits_source),
    .io_tilelink_a_bits_address (io_protocol_0_in_0_a_bits_address),
    .io_tilelink_a_bits_mask    (io_protocol_0_in_0_a_bits_mask),
    .io_tilelink_a_bits_data    (io_protocol_0_in_0_a_bits_data),
    .io_tilelink_a_bits_corrupt (io_protocol_0_in_0_a_bits_corrupt),
    .io_tilelink_b_ready        (io_protocol_0_in_0_b_ready),
    .io_tilelink_c_valid        (io_protocol_0_in_0_c_valid),
    .io_tilelink_c_bits_opcode  (io_protocol_0_in_0_c_bits_opcode),
    .io_tilelink_c_bits_param   (io_protocol_0_in_0_c_bits_param),
    .io_tilelink_c_bits_size    (io_protocol_0_in_0_c_bits_size),
    .io_tilelink_c_bits_source  (io_protocol_0_in_0_c_bits_source),
    .io_tilelink_c_bits_address (io_protocol_0_in_0_c_bits_address),
    .io_tilelink_c_bits_data    (io_protocol_0_in_0_c_bits_data),
    .io_tilelink_c_bits_corrupt (io_protocol_0_in_0_c_bits_corrupt),
    .io_tilelink_d_ready        (io_protocol_0_in_0_d_ready),
    .io_tilelink_e_valid        (io_protocol_0_in_0_e_valid),
    .io_tilelink_e_bits_sink    (io_protocol_0_in_0_e_bits_sink),
    .io_flits_a_ready           (_noc_io_ingress_0_flit_ready),	// Protocol.scala:105:19
    .io_flits_b_valid           (_noc_io_egress_0_flit_valid),	// Protocol.scala:105:19
    .io_flits_b_bits_head       (_noc_io_egress_0_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_b_bits_tail       (_noc_io_egress_0_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_b_bits_payload    (_noc_io_egress_0_flit_bits_payload),	// Protocol.scala:105:19
    .io_flits_c_ready           (_noc_io_ingress_1_flit_ready),	// Protocol.scala:105:19
    .io_flits_d_valid           (_noc_io_egress_1_flit_valid),	// Protocol.scala:105:19
    .io_flits_d_bits_head       (_noc_io_egress_1_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_d_bits_tail       (_noc_io_egress_1_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_d_bits_payload    (_noc_io_egress_1_flit_bits_payload),	// Protocol.scala:105:19
    .io_flits_e_ready           (_noc_io_ingress_2_flit_ready),	// Protocol.scala:105:19
    .io_tilelink_a_ready        (io_protocol_0_in_0_a_ready),
    .io_tilelink_b_valid        (io_protocol_0_in_0_b_valid),
    .io_tilelink_b_bits_opcode  (io_protocol_0_in_0_b_bits_opcode),
    .io_tilelink_b_bits_param   (io_protocol_0_in_0_b_bits_param),
    .io_tilelink_b_bits_size    (io_protocol_0_in_0_b_bits_size),
    .io_tilelink_b_bits_source  (io_protocol_0_in_0_b_bits_source),
    .io_tilelink_b_bits_address (io_protocol_0_in_0_b_bits_address),
    .io_tilelink_b_bits_mask    (io_protocol_0_in_0_b_bits_mask),
    .io_tilelink_b_bits_data    (io_protocol_0_in_0_b_bits_data),
    .io_tilelink_b_bits_corrupt (io_protocol_0_in_0_b_bits_corrupt),
    .io_tilelink_c_ready        (io_protocol_0_in_0_c_ready),
    .io_tilelink_d_valid        (io_protocol_0_in_0_d_valid),
    .io_tilelink_d_bits_opcode  (io_protocol_0_in_0_d_bits_opcode),
    .io_tilelink_d_bits_param   (io_protocol_0_in_0_d_bits_param),
    .io_tilelink_d_bits_size    (io_protocol_0_in_0_d_bits_size),
    .io_tilelink_d_bits_source  (io_protocol_0_in_0_d_bits_source),
    .io_tilelink_d_bits_sink    (io_protocol_0_in_0_d_bits_sink),
    .io_tilelink_d_bits_denied  (io_protocol_0_in_0_d_bits_denied),
    .io_tilelink_d_bits_data    (io_protocol_0_in_0_d_bits_data),
    .io_tilelink_d_bits_corrupt (io_protocol_0_in_0_d_bits_corrupt),
    .io_tilelink_e_ready        (io_protocol_0_in_0_e_ready),
    .io_flits_a_valid           (_nif_master_io_flits_a_valid),
    .io_flits_a_bits_head       (_nif_master_io_flits_a_bits_head),
    .io_flits_a_bits_tail       (_nif_master_io_flits_a_bits_tail),
    .io_flits_a_bits_payload    (_nif_master_io_flits_a_bits_payload),
    .io_flits_a_bits_egress_id  (_nif_master_io_flits_a_bits_egress_id),
    .io_flits_b_ready           (_nif_master_io_flits_b_ready),
    .io_flits_c_valid           (_nif_master_io_flits_c_valid),
    .io_flits_c_bits_head       (_nif_master_io_flits_c_bits_head),
    .io_flits_c_bits_tail       (_nif_master_io_flits_c_bits_tail),
    .io_flits_c_bits_payload    (_nif_master_io_flits_c_bits_payload),
    .io_flits_d_ready           (_nif_master_io_flits_d_ready),
    .io_flits_e_valid           (_nif_master_io_flits_e_valid),
    .io_flits_e_bits_head       (_nif_master_io_flits_e_bits_head),
    .io_flits_e_bits_payload    (_nif_master_io_flits_e_bits_payload)
  );
  TLSlaveToNoC nif_slave (	// Tilelink.scala:357:33
    .clock                      (clock),
    .reset                      (reset),
    .io_tilelink_a_ready        (io_protocol_0_out_0_a_ready),
    .io_tilelink_d_valid        (io_protocol_0_out_0_d_valid),
    .io_tilelink_d_bits_opcode  (io_protocol_0_out_0_d_bits_opcode),
    .io_tilelink_d_bits_param   (io_protocol_0_out_0_d_bits_param),
    .io_tilelink_d_bits_size    (io_protocol_0_out_0_d_bits_size),
    .io_tilelink_d_bits_source  (io_protocol_0_out_0_d_bits_source),
    .io_tilelink_d_bits_sink    ({2'h0, io_protocol_0_out_0_d_bits_sink}),	// Tilelink.scala:368:35
    .io_tilelink_d_bits_denied  (io_protocol_0_out_0_d_bits_denied),
    .io_tilelink_d_bits_data    (io_protocol_0_out_0_d_bits_data),
    .io_tilelink_d_bits_corrupt (io_protocol_0_out_0_d_bits_corrupt),
    .io_flits_a_valid           (_noc_io_egress_2_flit_valid),	// Protocol.scala:105:19
    .io_flits_a_bits_head       (_noc_io_egress_2_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_a_bits_tail       (_noc_io_egress_2_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_a_bits_payload    (_noc_io_egress_2_flit_bits_payload),	// Protocol.scala:105:19
    .io_flits_c_valid           (_noc_io_egress_3_flit_valid),	// Protocol.scala:105:19
    .io_flits_c_bits_head       (_noc_io_egress_3_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_c_bits_tail       (_noc_io_egress_3_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_d_ready           (_noc_io_ingress_4_flit_ready),	// Protocol.scala:105:19
    .io_flits_e_valid           (_noc_io_egress_4_flit_valid),	// Protocol.scala:105:19
    .io_flits_e_bits_head       (_noc_io_egress_4_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_e_bits_tail       (_noc_io_egress_4_flit_bits_tail),	// Protocol.scala:105:19
    .io_tilelink_a_valid        (io_protocol_0_out_0_a_valid),
    .io_tilelink_a_bits_opcode  (io_protocol_0_out_0_a_bits_opcode),
    .io_tilelink_a_bits_param   (io_protocol_0_out_0_a_bits_param),
    .io_tilelink_a_bits_size    (io_protocol_0_out_0_a_bits_size),
    .io_tilelink_a_bits_source  (io_protocol_0_out_0_a_bits_source),
    .io_tilelink_a_bits_address (_nif_slave_io_tilelink_a_bits_address),
    .io_tilelink_a_bits_mask    (io_protocol_0_out_0_a_bits_mask),
    .io_tilelink_a_bits_data    (io_protocol_0_out_0_a_bits_data),
    .io_tilelink_a_bits_corrupt (io_protocol_0_out_0_a_bits_corrupt),
    .io_tilelink_d_ready        (io_protocol_0_out_0_d_ready),
    .io_flits_a_ready           (_nif_slave_io_flits_a_ready),
    .io_flits_b_valid           (_nif_slave_io_flits_b_valid),
    .io_flits_b_bits_head       (_nif_slave_io_flits_b_bits_head),
    .io_flits_b_bits_tail       (_nif_slave_io_flits_b_bits_tail),
    .io_flits_b_bits_payload    (_nif_slave_io_flits_b_bits_payload),
    .io_flits_c_ready           (_nif_slave_io_flits_c_ready),
    .io_flits_d_valid           (_nif_slave_io_flits_d_valid),
    .io_flits_d_bits_head       (_nif_slave_io_flits_d_bits_head),
    .io_flits_d_bits_tail       (_nif_slave_io_flits_d_bits_tail),
    .io_flits_d_bits_payload    (_nif_slave_io_flits_d_bits_payload),
    .io_flits_e_ready           (_nif_slave_io_flits_e_ready)
  );
  TLSlaveToNoC_1 nif_slave_1 (	// Tilelink.scala:357:33
    .clock                      (clock),
    .reset                      (reset),
    .io_tilelink_a_ready        (io_protocol_0_out_1_a_ready),
    .io_tilelink_b_valid        (io_protocol_0_out_1_b_valid),
    .io_tilelink_b_bits_param   (io_protocol_0_out_1_b_bits_param),
    .io_tilelink_b_bits_size    (4'h6),	// Tilelink.scala:330:34
    .io_tilelink_b_bits_address (io_protocol_0_out_1_b_bits_address),
    .io_tilelink_c_ready        (io_protocol_0_out_1_c_ready),
    .io_tilelink_d_valid        (io_protocol_0_out_1_d_valid),
    .io_tilelink_d_bits_opcode  (io_protocol_0_out_1_d_bits_opcode),
    .io_tilelink_d_bits_param   (io_protocol_0_out_1_d_bits_param),
    .io_tilelink_d_bits_size    ({1'h0, io_protocol_0_out_1_d_bits_size}),	// Tilelink.scala:368:35
    .io_tilelink_d_bits_source  (io_protocol_0_out_1_d_bits_source),
    .io_tilelink_d_bits_sink    (io_protocol_0_out_1_d_bits_sink),
    .io_tilelink_d_bits_denied  (io_protocol_0_out_1_d_bits_denied),
    .io_tilelink_d_bits_data    (io_protocol_0_out_1_d_bits_data),
    .io_tilelink_d_bits_corrupt (io_protocol_0_out_1_d_bits_corrupt),
    .io_flits_a_valid           (_noc_io_egress_5_flit_valid),	// Protocol.scala:105:19
    .io_flits_a_bits_head       (_noc_io_egress_5_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_a_bits_tail       (_noc_io_egress_5_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_a_bits_payload    (_noc_io_egress_5_flit_bits_payload),	// Protocol.scala:105:19
    .io_flits_b_ready           (_noc_io_ingress_5_flit_ready),	// Protocol.scala:105:19
    .io_flits_c_valid           (_noc_io_egress_6_flit_valid),	// Protocol.scala:105:19
    .io_flits_c_bits_head       (_noc_io_egress_6_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_c_bits_tail       (_noc_io_egress_6_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_c_bits_payload    (_noc_io_egress_6_flit_bits_payload),	// Protocol.scala:105:19
    .io_flits_d_ready           (_noc_io_ingress_6_flit_ready),	// Protocol.scala:105:19
    .io_flits_e_valid           (_noc_io_egress_7_flit_valid),	// Protocol.scala:105:19
    .io_flits_e_bits_head       (_noc_io_egress_7_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_e_bits_tail       (_noc_io_egress_7_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_e_bits_payload    (_noc_io_egress_7_flit_bits_payload),	// Protocol.scala:105:19
    .io_tilelink_a_valid        (io_protocol_0_out_1_a_valid),
    .io_tilelink_a_bits_opcode  (io_protocol_0_out_1_a_bits_opcode),
    .io_tilelink_a_bits_param   (io_protocol_0_out_1_a_bits_param),
    .io_tilelink_a_bits_size    (_nif_slave_1_io_tilelink_a_bits_size),
    .io_tilelink_a_bits_source  (io_protocol_0_out_1_a_bits_source),
    .io_tilelink_a_bits_address (io_protocol_0_out_1_a_bits_address),
    .io_tilelink_a_bits_mask    (io_protocol_0_out_1_a_bits_mask),
    .io_tilelink_a_bits_data    (io_protocol_0_out_1_a_bits_data),
    .io_tilelink_a_bits_corrupt (io_protocol_0_out_1_a_bits_corrupt),
    .io_tilelink_b_ready        (io_protocol_0_out_1_b_ready),
    .io_tilelink_c_valid        (io_protocol_0_out_1_c_valid),
    .io_tilelink_c_bits_opcode  (io_protocol_0_out_1_c_bits_opcode),
    .io_tilelink_c_bits_param   (io_protocol_0_out_1_c_bits_param),
    .io_tilelink_c_bits_size    (_nif_slave_1_io_tilelink_c_bits_size),
    .io_tilelink_c_bits_source  (io_protocol_0_out_1_c_bits_source),
    .io_tilelink_c_bits_address (io_protocol_0_out_1_c_bits_address),
    .io_tilelink_c_bits_data    (io_protocol_0_out_1_c_bits_data),
    .io_tilelink_c_bits_corrupt (io_protocol_0_out_1_c_bits_corrupt),
    .io_tilelink_d_ready        (io_protocol_0_out_1_d_ready),
    .io_tilelink_e_valid        (io_protocol_0_out_1_e_valid),
    .io_tilelink_e_bits_sink    (io_protocol_0_out_1_e_bits_sink),
    .io_flits_a_ready           (_nif_slave_1_io_flits_a_ready),
    .io_flits_b_valid           (_nif_slave_1_io_flits_b_valid),
    .io_flits_b_bits_head       (_nif_slave_1_io_flits_b_bits_head),
    .io_flits_b_bits_tail       (_nif_slave_1_io_flits_b_bits_tail),
    .io_flits_b_bits_payload    (_nif_slave_1_io_flits_b_bits_payload),
    .io_flits_c_ready           (_nif_slave_1_io_flits_c_ready),
    .io_flits_d_valid           (_nif_slave_1_io_flits_d_valid),
    .io_flits_d_bits_head       (_nif_slave_1_io_flits_d_bits_head),
    .io_flits_d_bits_tail       (_nif_slave_1_io_flits_d_bits_tail),
    .io_flits_d_bits_payload    (_nif_slave_1_io_flits_d_bits_payload)
  );
  TLSlaveToNoC_2 nif_slave_2 (	// Tilelink.scala:357:33
    .clock                      (clock),
    .reset                      (reset),
    .io_tilelink_a_ready        (io_protocol_0_out_2_a_ready),
    .io_tilelink_d_valid        (io_protocol_0_out_2_d_valid),
    .io_tilelink_d_bits_opcode  (io_protocol_0_out_2_d_bits_opcode),
    .io_tilelink_d_bits_param   (io_protocol_0_out_2_d_bits_param),
    .io_tilelink_d_bits_size    ({1'h0, io_protocol_0_out_2_d_bits_size}),	// Tilelink.scala:368:35
    .io_tilelink_d_bits_source  (io_protocol_0_out_2_d_bits_source),
    .io_tilelink_d_bits_sink    ({2'h0, io_protocol_0_out_2_d_bits_sink}),	// Tilelink.scala:368:35
    .io_tilelink_d_bits_denied  (io_protocol_0_out_2_d_bits_denied),
    .io_tilelink_d_bits_data    (io_protocol_0_out_2_d_bits_data),
    .io_tilelink_d_bits_corrupt (io_protocol_0_out_2_d_bits_corrupt),
    .io_flits_a_valid           (_noc_io_egress_8_flit_valid),	// Protocol.scala:105:19
    .io_flits_a_bits_head       (_noc_io_egress_8_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_a_bits_tail       (_noc_io_egress_8_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_a_bits_payload    (_noc_io_egress_8_flit_bits_payload),	// Protocol.scala:105:19
    .io_flits_c_valid           (_noc_io_egress_9_flit_valid),	// Protocol.scala:105:19
    .io_flits_c_bits_head       (_noc_io_egress_9_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_c_bits_tail       (_noc_io_egress_9_flit_bits_tail),	// Protocol.scala:105:19
    .io_flits_d_ready           (_noc_io_ingress_8_flit_ready),	// Protocol.scala:105:19
    .io_flits_e_valid           (_noc_io_egress_10_flit_valid),	// Protocol.scala:105:19
    .io_flits_e_bits_head       (_noc_io_egress_10_flit_bits_head),	// Protocol.scala:105:19
    .io_flits_e_bits_tail       (_noc_io_egress_10_flit_bits_tail),	// Protocol.scala:105:19
    .io_tilelink_a_valid        (io_protocol_0_out_2_a_valid),
    .io_tilelink_a_bits_opcode  (io_protocol_0_out_2_a_bits_opcode),
    .io_tilelink_a_bits_param   (io_protocol_0_out_2_a_bits_param),
    .io_tilelink_a_bits_size    (_nif_slave_2_io_tilelink_a_bits_size),
    .io_tilelink_a_bits_source  (io_protocol_0_out_2_a_bits_source),
    .io_tilelink_a_bits_address (_nif_slave_2_io_tilelink_a_bits_address),
    .io_tilelink_a_bits_mask    (io_protocol_0_out_2_a_bits_mask),
    .io_tilelink_a_bits_data    (io_protocol_0_out_2_a_bits_data),
    .io_tilelink_a_bits_corrupt (io_protocol_0_out_2_a_bits_corrupt),
    .io_tilelink_d_ready        (io_protocol_0_out_2_d_ready),
    .io_flits_a_ready           (_nif_slave_2_io_flits_a_ready),
    .io_flits_b_valid           (_nif_slave_2_io_flits_b_valid),
    .io_flits_b_bits_head       (_nif_slave_2_io_flits_b_bits_head),
    .io_flits_b_bits_tail       (_nif_slave_2_io_flits_b_bits_tail),
    .io_flits_b_bits_payload    (_nif_slave_2_io_flits_b_bits_payload),
    .io_flits_c_ready           (_nif_slave_2_io_flits_c_ready),
    .io_flits_d_valid           (_nif_slave_2_io_flits_d_valid),
    .io_flits_d_bits_head       (_nif_slave_2_io_flits_d_bits_head),
    .io_flits_d_bits_tail       (_nif_slave_2_io_flits_d_bits_tail),
    .io_flits_d_bits_payload    (_nif_slave_2_io_flits_d_bits_payload),
    .io_flits_e_ready           (_nif_slave_2_io_flits_e_ready)
  );
  assign io_protocol_0_out_2_a_bits_size = _nif_slave_2_io_tilelink_a_bits_size[2:0];	// Tilelink.scala:357:33, :367:29
  assign io_protocol_0_out_2_a_bits_address =
    _nif_slave_2_io_tilelink_a_bits_address[30:0];	// Tilelink.scala:357:33, :367:29
  assign io_protocol_0_out_1_a_bits_size = _nif_slave_1_io_tilelink_a_bits_size[2:0];	// Tilelink.scala:357:33, :367:29
  assign io_protocol_0_out_1_c_bits_size = _nif_slave_1_io_tilelink_c_bits_size[2:0];	// Tilelink.scala:357:33, :372:31
  assign io_protocol_0_out_0_a_bits_address = _nif_slave_io_tilelink_a_bits_address[25:0];	// Tilelink.scala:357:33, :367:29
endmodule

